[package]
name = "wabou-shell"
version.workspace = true
edition = "2024"

license.workspace = true

[lib]
name = "wabou_shell"
path = "src/lib.rs"

[dependencies]
arboard = { workspace = true }
bitflags = { workspace = true }
directories = { workspace = true }
image = { workspace = true, features = ["ico", "jpeg", "png", "webp"] }
lru = "0.18.1"
notify-rust = { workspace = true }
open = { workspace = true }
parley = { workspace = true }
pollster = "0.4"
rfd = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
slotmap = { workspace = true }
snafu = { workspace = true }
taffy = { workspace = true, features = ["content_size", "parse"] }
tracing = { workspace = true }
unicode-segmentation = "1.12"
url = { workspace = true }
vello = { workspace = true }
vello_svg = { version = "0.10.0", default-features = false }
wgpu_context = "0.7"
winit = { workspace = true }
wabou-accessibility = { workspace = true }
wabou-host-api = { workspace = true }

[features]
profiling = []

[dev-dependencies]
tempfile = "3"
