import { defineWabouConfig } from "@wabou/vite";

export default defineWabouConfig({
  ignoreClasses: ["lucide", "lucide-*"],
  outDir: "../../dist/timestow/resources",
  globalName: "TimestowApp",
  theme: {
    default: "light",
    themes: {
      light: {
        appearance: "light",
        colors: {
          canvas: "#f3f6fa",
          surface: "#ffffff",
          "surface-muted": "#f7f9fc",
          input: "#ffffff",
          control: "#eef3f8",
          "control-hover": "#e5edf6",
          "control-pressed": "#d9e5f1",
          selected: "#e4effc",
          primary: "#162235",
          secondary: "#526279",
          muted: "#627185",
          subtle: "#d8e0ea",
          strong: "#aab7c7",
          accent: "#2674c8",
          "accent-hover": "#1d64b2",
          "accent-pressed": "#185493",
          "on-accent": "#ffffff",
          danger: "#c53c3c",
          "danger-hover": "#a83131",
          "danger-pressed": "#8c2929",
          "danger-surface": "#fff1f1",
          "danger-primary": "#a83131",
          "success-surface": "#eaf8f1",
          "success-primary": "#187454",
          focus: "#2674c8",
        },
      },
      dark: {
        appearance: "dark",
        colors: {
          canvas: "#10151d",
          surface: "#171e28",
          "surface-muted": "#1d2632",
          input: "#1d2632",
          control: "#222d3b",
          "control-hover": "#2a3747",
          "control-pressed": "#324357",
          selected: "#203c59",
          primary: "#edf3fa",
          secondary: "#bac6d5",
          muted: "#8998ab",
          subtle: "#2c3949",
          strong: "#46566a",
          accent: "#5aa6f2",
          "accent-hover": "#76b6f5",
          "accent-pressed": "#3f8dd9",
          "on-accent": "#08131f",
          danger: "#ef6a6a",
          "danger-hover": "#f18484",
          "danger-pressed": "#d95656",
          "danger-surface": "#3a2024",
          "danger-primary": "#ffaaaa",
          "success-surface": "#173129",
          "success-primary": "#77d6ae",
          focus: "#73b8ff",
        },
      },
    },
  },
});
