[package]
name = "wabou-host-api"
version.workspace = true
edition = "2024"
license.workspace = true

[features]
bindings = [
  "dep:specta",
  "dep:specta-typescript",
  "dep:wabou-bindgen",
  "wabou-bindgen/generate",
]

[dependencies]
serde = { workspace = true, features = ["derive"] }
specta = { workspace = true, optional = true }
specta-typescript = { workspace = true, optional = true }
wabou-bindgen = { workspace = true, optional = true }

[[example]]
name = "native-host-bindings"
path = "examples/native-host-bindings.rs"
required-features = ["bindings"]
