import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const root = resolve(import.meta.dir, "../../..");
const matrix = JSON.parse(
  await readFile(
    resolve(root, "packages/vite/src/style-compiler/css-support-matrix.json"),
    "utf8",
  ),
) as { supported: Record<string, unknown> };

type Contract = {
  string: boolean;
  number: boolean;
  typed: number[];
};

const PX = 1;
const PERCENT = 2;
const NUMBER = 3;
const COLOR = 5;
const AUTO = 6;
const contract: Record<string, Contract> = {};
const add = (
  properties: readonly string[],
  value: Omit<Contract, "typed"> & { typed?: number[] },
) => {
  for (const property of properties) {
    if (!(property in matrix.supported)) {
      throw new Error(
        `inline style property ${property} is absent from matrix`,
      );
    }
    contract[property] = { ...value, typed: value.typed ?? [] };
  }
};

add(
  [
    "display",
    "flex-direction",
    "justify-content",
    "align-items",
    "align-content",
    "align-self",
    "flex-wrap",
    "position",
    "overflow",
    "overflow-x",
    "overflow-y",
    "white-space",
    "text-overflow",
    "text-align",
    "pointer-events",
    "font-family",
    "cursor",
    "user-select",
  ],
  { string: true, number: false },
);
add(
  [
    "width",
    "height",
    "min-width",
    "min-height",
    "max-width",
    "max-height",
    "flex-basis",
    "top",
    "right",
    "bottom",
    "left",
    "margin",
    "margin-top",
    "margin-right",
    "margin-bottom",
    "margin-left",
    "margin-inline-start",
    "margin-inline-end",
  ],
  { string: true, number: true, typed: [PX, PERCENT, NUMBER, AUTO] },
);
add(
  [
    "gap",
    "row-gap",
    "column-gap",
    "padding",
    "padding-top",
    "padding-right",
    "padding-bottom",
    "padding-left",
  ],
  { string: true, number: true, typed: [PX, PERCENT, NUMBER] },
);
add(
  [
    "border-radius",
    "border-top-left-radius",
    "border-top-right-radius",
    "border-bottom-right-radius",
    "border-bottom-left-radius",
    "border-width",
    "border-top-width",
    "border-right-width",
    "border-bottom-width",
    "border-left-width",
    "font-size",
    "filter-blur",
    "backdrop-blur",
  ],
  { string: true, number: true, typed: [PX] },
);
add(["line-height"], {
  string: true,
  number: true,
  typed: [PX, NUMBER],
});
add(["flex-grow", "flex-shrink", "aspect-ratio", "opacity", "z-index"], {
  string: true,
  number: true,
  typed: [NUMBER],
});
add(
  [
    "grid-column-start",
    "grid-column-end",
    "grid-row-start",
    "grid-row-end",
  ],
  { string: true, number: true, typed: [NUMBER] },
);
add(["font-weight"], {
  string: true,
  number: true,
  typed: [NUMBER],
});
add(["font-style"], {
  string: true,
  number: false,
});
add(["text-decoration-line"], {
  string: true,
  number: false,
});
add(["letter-spacing"], {
  string: true,
  number: true,
  typed: [PX],
});
add(["background", "background-color", "color", "border-color"], {
  string: true,
  number: false,
  typed: [COLOR],
});

const missing = Object.keys(matrix.supported).filter(
  (property) =>
    !(property in contract) &&
    ![
      "grid-template-columns",
      "grid-template-rows",
      "grid-template",
      "box-shadow",
      "gap-x",
      "gap-y",
    ].includes(property),
);
if (missing.length) {
  throw new Error(
    `classify new inline style properties: ${missing.join(", ")}`,
  );
}

const json = JSON.stringify(
  Object.fromEntries(
    Object.entries(contract).sort(([a], [b]) => a.localeCompare(b)),
  ),
  null,
  2,
);
const output = `// AUTO-GENERATED by scripts/gen-style-properties.ts.\n\nexport const INLINE_STYLE_CONTRACT = ${json} as const;\n\ntype Contract = (typeof INLINE_STYLE_CONTRACT)[keyof typeof INLINE_STYLE_CONTRACT];\ntype TypedKind<C extends Contract> = C["typed"][number];\ntype TypedValue<K extends number> = {\n  readonly __wabou_style_value__: true;\n  readonly kind: K;\n  readonly value: number;\n};\ntype InlineValue<C extends Contract> =\n  | (C["string"] extends true ? string : never)\n  | (C["number"] extends true ? number : never)\n  | ([TypedKind<C>] extends [never] ? never : TypedValue<TypedKind<C>>)\n  | null\n  | undefined;\n\nexport type WabouStyle = {\n  [P in keyof typeof INLINE_STYLE_CONTRACT]?: InlineValue<(typeof INLINE_STYLE_CONTRACT)[P]>;\n};\n`;
const outputPath = resolve(
  root,
  "packages/core/src/style/generated/style-properties.ts",
);
await writeFile(outputPath, output);

const formatProcess = Bun.spawn(
  [Bun.which("bun") ?? "bun", "x", "biome", "format", "--write", outputPath],
  { cwd: root, stdout: "inherit", stderr: "inherit" },
);
if ((await formatProcess.exited) !== 0) {
  throw new Error("failed to format generated inline style declarations");
}
console.log("generated strict inline style properties");
