import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const root = resolve(import.meta.dir, "../../..");

const manifestCommand = [
  "cargo",
  "run",
  "-q",
  "-p",
  "wabou-style",
  "--bin",
  "wabou-style-manifest",
];
if (Bun.env.WABOU_THEME)
  manifestCommand.push("--", "--theme", Bun.env.WABOU_THEME);
const manifestProcess = Bun.spawn(manifestCommand, {
  cwd: root,
  stdout: "pipe",
  stderr: "inherit",
});
const json = await new Response(manifestProcess.stdout).text();
if ((await manifestProcess.exited) !== 0)
  throw new Error("failed to export utility manifest");
const manifest = JSON.parse(json) as {
  spacing: Record<string, number>;
  colors: Record<string, number>;
  staticUtilities: Record<string, { property: string }[]>;
  dynamicRules: {
    resolver: string;
    prefixes: { name: string; properties: string[] }[];
  }[];
};
await writeFile(
  resolve(root, "packages/vite/src/preset/manifest.json"),
  json,
);

const union = (values: string[]) =>
  values.length
    ? values.map((value) => JSON.stringify(value)).join(" | ")
    : "never";
const prefixes = (resolver: string) =>
  manifest.dynamicRules
    .find((rule) => rule.resolver === resolver)
    ?.prefixes.map(({ name }) => name) ?? [];
const negativePrefixes = (resolver: string, properties: string[]) =>
  manifest.dynamicRules
    .find((rule) => rule.resolver === resolver)
    ?.prefixes.filter(({ properties: emitted }) =>
      emitted.every((property) =>
        properties.some((prefix) => property.startsWith(prefix)),
      ),
    )
    .map(({ name }) => name) ?? [];
const types = `// AUTO-GENERATED by scripts/gen-utility-manifest.ts. Do not edit.
export type WabouStaticUtility = ${union(Object.keys(manifest.staticUtilities))};
export type WabouSpacingToken = ${union(Object.keys(manifest.spacing))};
export type WabouColorToken = ${union(Object.keys(manifest.colors))};

type ArbitraryLength = \`[\${number}px]\` | \`[\${number}rem]\` | \`[\${number}%]\`;
type BarePercent = \`\${number}%\`;
type ArbitraryColor = \`[#\${string}]\`;
type SpacingPrefix = ${union(prefixes("spacing"))};
type DimensionPrefix = ${union(prefixes("dimension"))};
type ColorPrefix = ${union(prefixes("color"))};
type NumberPrefix = ${union(prefixes("number"))};
type RatioPrefix = ${union(prefixes("ratio"))};
type LengthPrefix = ${union(prefixes("length"))};
type TranslatePrefix = ${union(prefixes("translate"))};
type ScalePrefix = ${union(prefixes("scale"))};
type RotatePrefix = ${union(prefixes("rotate"))};
type NegativeSpacingPrefix = ${union(negativePrefixes("spacing", ["margin-"]))};
type AutoSpacingPrefix = NegativeSpacingPrefix;
type NegativeDimensionPrefix = ${union(negativePrefixes("dimension", ["top", "right", "bottom", "left"]))};
export type WabouDynamicUtility =
  | \`\${SpacingPrefix}-\${WabouSpacingToken | ArbitraryLength}\`
  | \`\${AutoSpacingPrefix}-auto\`
  | \`\${DimensionPrefix}-\${WabouSpacingToken | ArbitraryLength | "full" | BarePercent}\`
  | \`-\${NegativeSpacingPrefix}-\${WabouSpacingToken | ArbitraryLength}\`
  | \`-\${NegativeDimensionPrefix}-\${WabouSpacingToken | ArbitraryLength | BarePercent}\`
  | \`\${ColorPrefix}-\${WabouColorToken}\`
  | \`\${ColorPrefix}-\${ArbitraryColor}\`
  | \`\${ColorPrefix}-\${WabouColorToken}/\${number}\`
  | \`\${NumberPrefix}-[\${number}]\`
  | \`\${RatioPrefix}-[\${number}]\`
  | \`\${RatioPrefix}-[\${number}/\${number}]\`
  | \`\${LengthPrefix}-\${ArbitraryLength}\`
  | \`\${TranslatePrefix}-\${WabouSpacingToken | ArbitraryLength}\`
  | \`-\${TranslatePrefix}-\${WabouSpacingToken | ArbitraryLength}\`
  | \`\${ScalePrefix}-\${number}\`
  | \`\${ScalePrefix}-[\${number}]\`
  | \`\${RotatePrefix}-\${number}\`
  | \`\${RotatePrefix}-[\${number}]\`
  | \`-\${RotatePrefix}-\${number}\`
  | \`opacity-\${number}\`;
export type WabouBaseUtility = WabouStaticUtility | WabouDynamicUtility;
export type WabouUtility = WabouBaseUtility;
`;
await mkdir(resolve(root, "packages/core/src/style/generated"), {
  recursive: true,
});
await writeFile(
  resolve(root, "packages/core/src/style/generated/utility-types.ts"),
  types,
);
const expandedProperties = (properties: string[]) =>
  properties.flatMap((property) => {
    switch (property) {
      case "border-width":
        return [
          "border-top-width",
          "border-right-width",
          "border-bottom-width",
          "border-left-width",
        ];
      case "gap":
        return ["row-gap", "column-gap"];
      case "overflow":
        return ["overflow-x", "overflow-y"];
      case "background":
        return ["background-color"];
      default:
        return [property];
    }
  });
const conflictData = `// AUTO-GENERATED by scripts/gen-utility-manifest.ts. Do not edit.
export const UTILITY_CONFLICT_DATA = ${JSON.stringify(
  {
    spacing: Object.keys(manifest.spacing),
    colors: Object.keys(manifest.colors),
    staticUtilities: Object.fromEntries(
      Object.entries(manifest.staticUtilities).map(([candidate, declarations]) => [
        candidate,
        [...new Set(expandedProperties(declarations.map(({ property }) => property)))],
      ]),
    ),
    dynamicRules: manifest.dynamicRules.flatMap(({ resolver, prefixes }) =>
      prefixes.map(({ name, properties }) => ({
        resolver,
        name,
        properties: [...new Set(expandedProperties(properties))],
        negative:
          resolver === "translate" ||
          resolver === "rotate" ||
          (resolver === "spacing" &&
            properties.every((property) => property.startsWith("margin-"))) ||
          (resolver === "dimension" &&
            properties.every((property) =>
              ["top", "right", "bottom", "left"].includes(property),
            )),
        auto:
          resolver === "spacing" &&
          properties.every((property) => property.startsWith("margin-")),
      })),
    ),
  },
  null,
  2,
)} as const;
`;
await writeFile(
  resolve(root, "packages/core/src/style/generated/utility-conflicts.ts"),
  conflictData,
);
const formatProcess = Bun.spawn(
  [
    Bun.which("bun") ?? "bun",
    "x",
    "biome",
    "format",
    "--write",
    resolve(root, "packages/core/src/style/generated/utility-types.ts"),
    resolve(root, "packages/core/src/style/generated/utility-conflicts.ts"),
  ],
  { cwd: root, stdout: "inherit", stderr: "inherit" },
);
if ((await formatProcess.exited) !== 0)
  throw new Error("failed to format generated utility types");
