import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const root = resolve(import.meta.dir, "../../..");

const manifestCommand = [
  "cargo",
  "run",
  "-q",
  "-p",
  "wabou-style",
  "--bin",
  "wabou-style-manifest",
];
if (Bun.env.WABOU_THEME)
  manifestCommand.push("--", "--theme", Bun.env.WABOU_THEME);
const manifestProcess = Bun.spawn(manifestCommand, {
  cwd: root,
  stdout: "pipe",
  stderr: "inherit",
});
const json = await new Response(manifestProcess.stdout).text();
if ((await manifestProcess.exited) !== 0)
  throw new Error("failed to export utility manifest");
const manifest = JSON.parse(json) as {
  spacing: Record<string, number>;
  colors: Record<string, number>;
  staticUtilities: Record<string, unknown>;
  dynamicRules: {
    resolver: string;
    prefixes: { name: string; properties: string[] }[];
  }[];
};
await writeFile(
  resolve(root, "packages/vite/src/preset/manifest.json"),
  json,
);

const union = (values: string[]) =>
  values.length
    ? values.map((value) => JSON.stringify(value)).join(" | ")
    : "never";
const prefixes = (resolver: string) =>
  manifest.dynamicRules
    .find((rule) => rule.resolver === resolver)
    ?.prefixes.map(({ name }) => name) ?? [];
const negativePrefixes = (resolver: string, properties: string[]) =>
  manifest.dynamicRules
    .find((rule) => rule.resolver === resolver)
    ?.prefixes.filter(({ properties: emitted }) =>
      emitted.every((property) =>
        properties.some((prefix) => property.startsWith(prefix)),
      ),
    )
    .map(({ name }) => name) ?? [];
const types = `// AUTO-GENERATED by scripts/gen-utility-manifest.ts. Do not edit.
export type WabouStaticUtility = ${union(Object.keys(manifest.staticUtilities))};
export type WabouSpacingToken = ${union(Object.keys(manifest.spacing))};
export type WabouColorToken = ${union(Object.keys(manifest.colors))};

type ArbitraryLength = \`[\${number}px]\` | \`[\${number}rem]\` | \`[\${number}%]\`;
type BarePercent = \`\${number}%\`;
type ArbitraryColor = \`[#\${string}]\`;
type SpacingPrefix = ${union(prefixes("spacing"))};
type DimensionPrefix = ${union(prefixes("dimension"))};
type ColorPrefix = ${union(prefixes("color"))};
type NumberPrefix = ${union(prefixes("number"))};
type RatioPrefix = ${union(prefixes("ratio"))};
type LengthPrefix = ${union(prefixes("length"))};
type TranslatePrefix = ${union(prefixes("translate"))};
type ScalePrefix = ${union(prefixes("scale"))};
type RotatePrefix = ${union(prefixes("rotate"))};
type NegativeSpacingPrefix = ${union(negativePrefixes("spacing", ["margin-"]))};
type AutoSpacingPrefix = NegativeSpacingPrefix;
type NegativeDimensionPrefix = ${union(negativePrefixes("dimension", ["top", "right", "bottom", "left"]))};
export type WabouDynamicUtility =
  | \`\${SpacingPrefix}-\${WabouSpacingToken | ArbitraryLength}\`
  | \`\${AutoSpacingPrefix}-auto\`
  | \`\${DimensionPrefix}-\${WabouSpacingToken | ArbitraryLength | "full" | BarePercent}\`
  | \`-\${NegativeSpacingPrefix}-\${WabouSpacingToken | ArbitraryLength}\`
  | \`-\${NegativeDimensionPrefix}-\${WabouSpacingToken | ArbitraryLength | BarePercent}\`
  | \`\${ColorPrefix}-\${WabouColorToken}\`
  | \`\${ColorPrefix}-\${ArbitraryColor}\`
  | \`\${ColorPrefix}-\${WabouColorToken}/\${number}\`
  | \`\${NumberPrefix}-[\${number}]\`
  | \`\${RatioPrefix}-[\${number}]\`
  | \`\${RatioPrefix}-[\${number}/\${number}]\`
  | \`\${LengthPrefix}-\${ArbitraryLength}\`
  | \`\${TranslatePrefix}-\${WabouSpacingToken | ArbitraryLength}\`
  | \`-\${TranslatePrefix}-\${WabouSpacingToken | ArbitraryLength}\`
  | \`\${ScalePrefix}-\${number}\`
  | \`\${ScalePrefix}-[\${number}]\`
  | \`\${RotatePrefix}-\${number}\`
  | \`\${RotatePrefix}-[\${number}]\`
  | \`-\${RotatePrefix}-\${number}\`
  | \`opacity-\${number}\`;
export type WabouBaseUtility = WabouStaticUtility | WabouDynamicUtility;
export type WabouUtility = WabouBaseUtility;
`;
await mkdir(resolve(root, "packages/style/generated"), {
  recursive: true,
});
await writeFile(
  resolve(root, "packages/style/generated/utility-types.ts"),
  types,
);
const formatProcess = Bun.spawn(
  [
    Bun.which("bun") ?? "bun",
    "x",
    "biome",
    "format",
    "--write",
    resolve(root, "packages/style/generated/utility-types.ts"),
  ],
  { cwd: root, stdout: "inherit", stderr: "inherit" },
);
if ((await formatProcess.exited) !== 0)
  throw new Error("failed to format generated utility types");
