[package]
name = "wabou-database"
version.workspace = true
edition = "2024"
license.workspace = true

[dependencies]
tokio = { workspace = true, features = ["sync"] }
turso = { version = "0.8.0-pre.3", default-features = false }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
uuid = { workspace = true }
