[package]
name = "wabou-devtools-app"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "wabou-devtools"
path = "src/main.rs"

[dependencies]
serde = { workspace = true, features = ["derive"] }
snafu = { workspace = true }
serde_json = { workspace = true }
specta = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
wabou-bindgen = { workspace = true }
wabou-devtools = { workspace = true, features = ["bindings"] }
wabou-runtime = { workspace = true }
