import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { ROOT, run, writeGenerated } from "../output.ts";

type Operation = {
  name: string;
  capability: number;
  method: number;
  description: string;
};

const sourcePath = resolve(ROOT, "packages/core/effect-abi.json");
const schema = JSON.parse(await readFile(sourcePath, "utf8")) as {
  schemaVersion: number;
  abiVersion: number;
  operations: Operation[];
};

if (schema.schemaVersion !== 1) {
  throw new Error(`unsupported Effect ABI schema v${schema.schemaVersion}`);
}
if (!Number.isInteger(schema.abiVersion) || schema.abiVersion <= 0 || schema.abiVersion > 0xffff) {
  throw new Error(`invalid Effect ABI version ${schema.abiVersion}`);
}

const names = new Set<string>();
const ids = new Set<string>();
for (const operation of schema.operations) {
  if (!/^[a-z][A-Za-z0-9]*$/.test(operation.name)) {
    throw new Error(`invalid Effect ABI operation name: ${operation.name}`);
  }
  if (names.has(operation.name)) {
    throw new Error(`duplicate Effect ABI operation name: ${operation.name}`);
  }
  names.add(operation.name);
  if (!operation.description.trim()) {
    throw new Error(`missing description for ${operation.name}`);
  }
  if (!Number.isInteger(operation.capability) || operation.capability <= 0 || operation.capability > 0xffffffff) {
    throw new Error(`invalid capability for ${operation.name}`);
  }
  if (!Number.isInteger(operation.method) || operation.method <= 0 || operation.method > 0xffff) {
    throw new Error(`invalid method for ${operation.name}`);
  }
  const id = `${operation.capability}:${operation.method}`;
  if (ids.has(id)) throw new Error(`duplicate Effect ABI operation id: ${id}`);
  ids.add(id);
}

const header = "// AUTO-GENERATED by scripts/codegen/protocol/effect-abi.ts. Do not edit by hand.\n";
const typescript = `${header}export const EFFECT_ABI_VERSION = ${schema.abiVersion} as const;

export const effectOps = Object.freeze({
${schema.operations.map((operation) => `  ${operation.name}: { capability: ${operation.capability}, method: ${operation.method} },`).join("\n")}
} as const);
`;

const rust = `${header}/// Wire schema version for serialized effect requests and completions.
pub const EFFECT_ABI_VERSION: u16 = ${schema.abiVersion};

${schema.operations.map((operation) => `/// ${operation.description}\npub const ${operation.name.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toUpperCase()}: crate::effect::EffectOp = crate::effect::EffectOp::new(${operation.capability}, ${operation.method});`).join("\n")}
`;

const tsPath = resolve(ROOT, "packages/core/src/generated/effect-abi.ts");
const rustPath = resolve(ROOT, "crates/wabou-shell/src/generated/effect_abi.rs");
await writeGenerated(tsPath, typescript);
await writeGenerated(rustPath, rust);
await run([Bun.which("bun") ?? "bun", "x", "biome", "format", "--write", tsPath], "format generated Effect ABI TypeScript");
await run(["rustfmt", "--edition", "2024", rustPath], "format generated Effect ABI Rust");
console.log(`generated ${schema.operations.length} effect operations`);
