// Application-facing Wabou API. The packages re-exported here remain useful
// implementation boundaries, but applications should not need to understand
// that package graph for ordinary UI work.

export * from "@wabou/core";
export * from "@wabou/core/i18n";
export * from "./animation";
export * from "./components";
// Prefer the styled component where a high-level component and a host-service
// type share a name. The lower-level host API remains available as `dialog`.
export { Dialog } from "./components";
export * from "./integrations";
export * as primitives from "./primitives";

// Foundational scene elements are common enough to belong at the main entry.
// Headless controls with names shared by styled components stay available
// from `@wabou/ui/primitives` and through the `primitives` namespace.
export {
  type ActiveResult,
  type AnimationFrameCallback,
  Button as PrimitiveButton,
  type ButtonProps as PrimitiveButtonProps,
  type ButtonState as PrimitiveButtonState,
  Center,
  CollapsiblePresence,
  Column,
  type ContainerMatch,
  type ContainerSizeQuery,
  createActive,
  createAnimationFrame,
  createButton,
  createContainerMatch,
  createFileImageResource,
  createFocus,
  createFocusWithin,
  createFormDraft,
  createHover,
  createKeyedSelection,
  createMeasuredSize,
  createNetworkImageResource,
  createNotifications,
  createOverlayLayer,
  createOwnedImageResource,
  createPresence,
  createPress,
  createRetainedItems,
  createScrollReset,
  createShortcuts,
  createTabs,
  createTransitionPresence,
  Editor,
  type EditorProps,
  FORM_ERROR,
  type FocusResult,
  type FocusWithinResult,
  type FormDraft,
  type FormDraftErrors,
  type FormDraftFieldUpdater,
  type FormDraftOptions,
  Icon,
  type IconProps,
  Image,
  type ImageProps,
  type ImageResourceDescriptor,
  type ImageResourceErrorEvent,
  type ImageResourceHandle,
  type ImageResourceReadyEvent,
  type ImageResourceRequest,
  type KeyedSelection,
  type KeyedSelectionOptions,
  type LayoutProps,
  Link as PrimitiveLink,
  type LinkProps as PrimitiveLinkProps,
  Modal,
  type ModalMotionOptions,
  type ModalProps,
  type NotificationMotionOptions,
  NotificationRegion,
  type NotificationRegionProps,
  type Notifications,
  type OverlayLayer,
  OverlayPlaneProvider,
  type OwnedImageResource,
  PasswordInput as PrimitivePasswordInput,
  type PasswordInputProps as PrimitivePasswordInputProps,
  Path,
  PathBuilder,
  type PathProps,
  Popover as PrimitivePopover,
  type PopoverProps as PrimitivePopoverProps,
  type PressResult,
  Pulse,
  type RetainedItem,
  type RetainedItems,
  RichText,
  type RichTextProps,
  RichTextSpan,
  type RichTextSpanProps,
  Ripple,
  type RippleProps,
  Row,
  releaseImageResource,
  ScrollArea,
  type ScrollAreaProps,
  Spin,
  Svg,
  type SvgProps,
  type TabsResult,
  Text,
  TextArea as PrimitiveTextArea,
  type TextAreaProps as PrimitiveTextAreaProps,
  TextInput as PrimitiveTextInput,
  type TextInputProps as PrimitiveTextInputProps,
  type TextProps,
  type TransitionPresence,
  type TransitionPresenceOptions,
  type VectorPath,
  type VectorPathPaint,
  View,
  type ViewProps,
  type WabouClassList,
  type WabouStyle,
} from "./primitives";
export * from "./router";
