//! Deterministic TypeScript clients and declarations for Wabou capabilities.
//!
//! A native QuickJS method may return immediately or through a Promise.
//! Generated clients normalize both forms to an asynchronous typed API and
//! own JSON serialization so application code only sees typed DTOs.

use std::any::TypeId;
use std::collections::{BTreeMap, BTreeSet};
use std::fmt;
use std::fs;
use std::path::{Path, PathBuf};

pub use ts_rs::{self, TS};
use ts_rs::{Config, TypeVisitor};

const HEADER: &str = "// AUTO-GENERATED by wabou-bindings. DO NOT EDIT.\n";

#[derive(Clone, Debug, Eq, PartialEq)]
struct TypeDeclaration {
    name: String,
    declaration: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Method {
    name: String,
    request: TypeDeclaration,
    response: TypeDeclaration,
    declarations: BTreeMap<String, String>,
}

impl Method {
    /// Describe one asynchronous JSON method on a native capability.
    pub fn json<Request, Response>(name: impl Into<String>) -> Self
    where
        Request: TS + 'static,
        Response: TS + 'static,
    {
        let name = name.into();
        assert_identifier(&name, "method");
        let mut collector = DeclarationCollector::default();
        let request = collector.register::<Request>();
        let response = collector.register::<Response>();
        Self {
            name,
            request,
            response,
            declarations: collector.declarations,
        }
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Capability {
    name: String,
    methods: Vec<Method>,
}

impl Capability {
    pub fn new(name: impl Into<String>) -> Self {
        let name = name.into();
        assert_identifier(&name, "capability");
        Self {
            name,
            methods: Vec::new(),
        }
    }

    pub fn method(mut self, method: Method) -> Self {
        assert!(
            self.methods
                .iter()
                .all(|current| current.name != method.name),
            "duplicate method `{}` in capability `{}`",
            method.name,
            self.name
        );
        self.methods.push(method);
        self
    }
}

#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct Bindings {
    capabilities: Vec<Capability>,
}

impl Bindings {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn capability(mut self, capability: Capability) -> Self {
        assert!(
            self.capabilities
                .iter()
                .all(|current| current.name != capability.name),
            "duplicate capability `{}`",
            capability.name
        );
        self.capabilities.push(capability);
        self
    }

    /// Render one deterministic module containing DTOs, raw Host augmentation,
    /// and typed JSON clients.
    pub fn render(&self) -> String {
        let mut output = String::from(HEADER);
        output.push_str("import type { Host } from \"@wabou/solid-renderer\";\n");
        output.push_str("import \"@wabou/solid-renderer\";\n\n");
        output.push_str(
            "export type NativeResult<T> = T | PromiseLike<T>;\n\n",
        );

        let declarations = self
            .capabilities
            .iter()
            .flat_map(|capability| &capability.methods)
            .flat_map(|method| &method.declarations)
            .map(|(name, declaration)| (name.clone(), declaration.clone()))
            .collect::<BTreeMap<_, _>>();
        for declaration in declarations.values() {
            output.push_str("export ");
            output.push_str(declaration.trim());
            output.push_str("\n\n");
        }

        output.push_str("declare module \"@wabou/solid-renderer\" {\n");
        output.push_str("  interface HostCapabilities {\n");
        for capability in sorted_capabilities(&self.capabilities) {
            output.push_str(&format!("    readonly {}: {{\n", capability.name));
            for method in sorted_methods(&capability.methods) {
                output.push_str(&format!(
                    "      {}(request: string): NativeResult<string>;\n",
                    method.name
                ));
            }
            output.push_str("    };\n");
        }
        output.push_str("  }\n}\n\n");

        for capability in sorted_capabilities(&self.capabilities) {
            let interface = format!("{}Client", upper_camel_case(&capability.name));
            output.push_str(&format!("export interface {interface} {{\n"));
            for method in sorted_methods(&capability.methods) {
                output.push_str(&format!(
                    "  {}(request: {}): Promise<{}>;\n",
                    method.name, method.request.name, method.response.name
                ));
            }
            output.push_str("}\n\n");
            output.push_str(&format!(
                "export function create{interface}(host: Host): {interface} {{\n"
            ));
            output.push_str("  return {\n");
            for method in sorted_methods(&capability.methods) {
                output.push_str(&format!(
                    "    {}: async (request) => JSON.parse(await host.{}.{}(JSON.stringify(request))) as {},\n",
                    method.name, capability.name, method.name, method.response.name
                ));
            }
            output.push_str("  };\n}\n\n");
        }
        output.truncate(output.trim_end().len());
        output.push('\n');
        output
    }

    pub fn write(&self, path: impl AsRef<Path>) -> Result<(), BindingsError> {
        let path = path.as_ref();
        if let Some(parent) = path
            .parent()
            .filter(|parent| !parent.as_os_str().is_empty())
        {
            fs::create_dir_all(parent).map_err(|source| BindingsError::Io {
                path: parent.to_path_buf(),
                source,
            })?;
        }
        fs::write(path, self.render()).map_err(|source| BindingsError::Io {
            path: path.to_path_buf(),
            source,
        })
    }

    pub fn check(&self, path: impl AsRef<Path>) -> Result<(), BindingsError> {
        let path = path.as_ref();
        let actual = fs::read_to_string(path).map_err(|source| BindingsError::Io {
            path: path.to_path_buf(),
            source,
        })?;
        let expected = self.render();
        if actual == expected {
            Ok(())
        } else {
            Err(BindingsError::Drift(path.to_path_buf()))
        }
    }
}

#[derive(Debug)]
pub enum BindingsError {
    Io {
        path: PathBuf,
        source: std::io::Error,
    },
    Drift(PathBuf),
}

impl fmt::Display for BindingsError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Io { path, source } => {
                write!(formatter, "cannot access {}: {source}", path.display())
            }
            Self::Drift(path) => write!(
                formatter,
                "generated bindings differ from {}; run `wabou bindings write`",
                path.display()
            ),
        }
    }
}

impl std::error::Error for BindingsError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Io { source, .. } => Some(source),
            Self::Drift(_) => None,
        }
    }
}

#[derive(Default)]
struct DeclarationCollector {
    visited: BTreeSet<TypeId>,
    declarations: BTreeMap<String, String>,
}

impl DeclarationCollector {
    fn register<T: TS + 'static + ?Sized>(&mut self) -> TypeDeclaration {
        let config = Config::new().with_large_int("number");
        let declaration = TypeDeclaration {
            name: T::name(&config),
            declaration: T::decl(&config),
        };
        if self.visited.insert(TypeId::of::<T>()) {
            let identifier = T::ident(&config);
            if let Some(previous) = self
                .declarations
                .insert(identifier.clone(), declaration.declaration.clone())
            {
                assert_eq!(
                    previous, declaration.declaration,
                    "different Rust types export the same TypeScript name `{identifier}`"
                );
            }
            T::visit_dependencies(self);
        }
        declaration
    }
}

impl TypeVisitor for DeclarationCollector {
    fn visit<T: TS + 'static + ?Sized>(&mut self) {
        if T::output_path().is_some() {
            self.register::<T>();
        }
    }
}

fn sorted_capabilities(capabilities: &[Capability]) -> Vec<&Capability> {
    let mut values = capabilities.iter().collect::<Vec<_>>();
    values.sort_by(|left, right| left.name.cmp(&right.name));
    values
}

fn sorted_methods(methods: &[Method]) -> Vec<&Method> {
    let mut values = methods.iter().collect::<Vec<_>>();
    values.sort_by(|left, right| left.name.cmp(&right.name));
    values
}

fn assert_identifier(value: &str, kind: &str) {
    let mut chars = value.chars();
    let valid_start = chars
        .next()
        .is_some_and(|character| character == '_' || character.is_ascii_alphabetic());
    let valid_tail = chars.all(|character| character == '_' || character.is_ascii_alphanumeric());
    assert!(
        valid_start && valid_tail,
        "invalid {kind} identifier `{value}`"
    );
}

fn upper_camel_case(value: &str) -> String {
    let mut result = String::new();
    let mut uppercase = true;
    for character in value.chars() {
        if character == '_' {
            uppercase = true;
        } else if uppercase {
            result.extend(character.to_uppercase());
            uppercase = false;
        } else {
            result.push(character);
        }
    }
    result
}

#[cfg(test)]
#[allow(dead_code)]
mod tests {
    use super::*;

    #[derive(TS)]
    struct Nested {
        value: String,
    }

    #[derive(TS)]
    struct Request {
        nested: Nested,
        count: u64,
    }

    #[derive(TS)]
    #[ts(rename_all = "camelCase")]
    enum Response {
        Accepted { display_name: String },
        Rejected,
    }

    fn fixture() -> Bindings {
        Bindings::new().capability(
            Capability::new("workspace").method(Method::json::<Request, Response>("readFile")),
        )
    }

    #[test]
    fn renders_dependencies_raw_abi_and_typed_client() {
        let output = fixture().render();
        assert!(output.contains("export type Nested ="));
        assert!(output.contains("count: number"));
        assert!(output.contains("export type NativeResult<T> = T | PromiseLike<T>"));
        assert!(output.contains("readFile(request: string): NativeResult<string>"));
        assert!(output.contains("readFile(request: Request): Promise<Response>"));
        assert!(output.contains("JSON.stringify(request)"));
        assert!(output.contains("JSON.parse(await host.workspace.readFile"));
    }

    #[test]
    fn check_reports_drift_without_rewriting_the_file() {
        let path = std::env::temp_dir().join(format!(
            "wabou-bindings-{}-{}.ts",
            std::process::id(),
            line!()
        ));
        fixture().write(&path).unwrap();
        fixture().check(&path).unwrap();
        fs::write(&path, "stale").unwrap();
        assert!(matches!(
            fixture().check(&path),
            Err(BindingsError::Drift(_))
        ));
        assert_eq!(fs::read_to_string(&path).unwrap(), "stale");
        fs::remove_file(path).unwrap();
    }
}
