//! Deterministic TypeScript clients and declarations for Wabou capabilities.
//!
//! A native QuickJS method may return immediately or through a Promise.
//! Generated clients normalize both forms to an asynchronous typed API and
//! own JSON serialization so application code only sees typed DTOs.

use std::any::TypeId;
use std::collections::{BTreeMap, BTreeSet};
use std::fmt;
use std::fs;
use std::path::{Path, PathBuf};

use specta::functions::FunctionDataType;
use specta::ts::{self, BigIntExportBehavior, ExportConfiguration};
pub use specta::{self, Type};
use specta::{DataType, PrimitiveType, TypeDefs};
pub use ts_rs::{self, TS};
use ts_rs::{Config, TypeVisitor};

const HEADER: &str = "// AUTO-GENERATED by wabou-bindings. DO NOT EDIT.\n";

#[derive(Clone, Debug, Eq, PartialEq)]
struct TypeDeclaration {
    name: String,
    declaration: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct Argument {
    name: String,
    ty: TypeDeclaration,
    json: bool,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Method {
    name: String,
    arguments: Vec<Argument>,
    response: TypeDeclaration,
    result_envelope: bool,
    declarations: BTreeMap<String, String>,
}

impl Method {
    /// Describe one asynchronous JSON method on a native capability.
    pub fn json<Request, Response>(name: impl Into<String>) -> Self
    where
        Request: TS + 'static,
        Response: TS + 'static,
    {
        let name = name.into();
        assert_identifier(&name, "method");
        let mut collector = DeclarationCollector::default();
        let request = collector.register::<Request>();
        let response = collector.register::<Response>();
        Self {
            name,
            arguments: vec![Argument {
                name: "request".into(),
                ty: request,
                json: true,
            }],
            response,
            result_envelope: false,
            declarations: collector.declarations,
        }
    }

    /// Describe an asynchronous JSON method whose response uses Wabou's
    /// `{ ok, value } | { ok, error }` native result envelope.
    pub fn json_result<Request, Response>(name: impl Into<String>) -> Self
    where
        Request: TS + 'static,
        Response: TS + 'static,
    {
        let mut method = Self::json::<Request, Response>(name);
        method.result_envelope = true;
        method
    }

    /// Describe a result method that acknowledges success with a boolean.
    pub fn json_result_ack<Request>(name: impl Into<String>) -> Self
    where
        Request: TS + 'static,
    {
        let name = name.into();
        assert_identifier(&name, "method");
        let mut collector = DeclarationCollector::default();
        let request = collector.register::<Request>();
        Self {
            name,
            arguments: vec![Argument {
                name: "request".into(),
                ty: request,
                json: true,
            }],
            response: TypeDeclaration {
                name: "boolean".into(),
                declaration: String::new(),
            },
            result_envelope: true,
            declarations: collector.declarations,
        }
    }

    /// Describe a no-argument JSON method.
    pub fn json_no_args<Response>(name: impl Into<String>) -> Self
    where
        Response: TS + 'static,
    {
        let name = name.into();
        assert_identifier(&name, "method");
        let mut collector = DeclarationCollector::default();
        let response = collector.register::<Response>();
        Self {
            name,
            arguments: Vec::new(),
            response,
            result_envelope: false,
            declarations: collector.declarations,
        }
    }

    /// Describe a no-argument method using Wabou's native result envelope.
    pub fn json_result_no_args<Response>(name: impl Into<String>) -> Self
    where
        Response: TS + 'static,
    {
        let mut method = Self::json_no_args::<Response>(name);
        method.result_envelope = true;
        method
    }

    /// Describe a no-argument result method whose successful value is nullable.
    pub fn json_result_no_args_nullable<Response>(name: impl Into<String>) -> Self
    where
        Response: TS + 'static,
    {
        let name = name.into();
        assert_identifier(&name, "method");
        let mut collector = DeclarationCollector::default();
        let inner = collector.register::<Response>();
        Self {
            name,
            arguments: Vec::new(),
            response: TypeDeclaration {
                name: format!("{} | null", inner.name),
                declaration: String::new(),
            },
            result_envelope: true,
            declarations: collector.declarations,
        }
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Capability {
    name: String,
    methods: Vec<Method>,
}

impl Capability {
    pub fn new(name: impl Into<String>) -> Self {
        let name = name.into();
        assert_identifier(&name, "capability");
        Self {
            name,
            methods: Vec::new(),
        }
    }

    pub fn method(mut self, method: Method) -> Self {
        assert!(
            self.methods
                .iter()
                .all(|current| current.name != method.name),
            "duplicate method `{}` in capability `{}`",
            method.name,
            self.name
        );
        self.methods.push(method);
        self
    }

    /// Build a capability directly from Rust functions annotated with
    /// `#[specta::specta]`. Function arguments and return DTOs become the
    /// typed client API; primitive arguments cross the native ABI directly
    /// while structured arguments are JSON encoded.
    pub fn from_specta(name: impl Into<String>, contract: impl IntoSpectaFunctions) -> Self {
        let (functions, type_defs) = contract
            .into_specta_functions()
            .unwrap_or_else(|error| panic!("invalid Specta function contract: {error}"));
        let mut capability = Self::new(name);
        let config = specta_config();
        let declarations = type_defs
            .values()
            .filter_map(Option::as_ref)
            .map(|datatype| {
                let declaration = ts::export_datatype(&config, datatype)
                    .unwrap_or_else(|error| panic!("cannot export `{}`: {error}", datatype.name));
                (
                    datatype.name.to_string(),
                    declaration
                        .strip_prefix("export ")
                        .unwrap_or(&declaration)
                        .to_string(),
                )
            })
            .collect::<BTreeMap<_, _>>();

        for function in functions {
            let method_name = lower_camel_case(function.name);
            let arguments = function
                .args
                .into_iter()
                .map(|(name, datatype)| Argument {
                    name: lower_camel_case(name),
                    ty: TypeDeclaration {
                        name: ts::datatype(&config, &datatype).unwrap_or_else(|error| {
                            panic!("cannot export argument `{name}`: {error}")
                        }),
                        declaration: String::new(),
                    },
                    json: !is_native_primitive(&datatype),
                })
                .collect();
            let response = TypeDeclaration {
                name: ts::datatype(&config, &function.result).unwrap_or_else(|error| {
                    panic!("cannot export result of `{}`: {error}", function.name)
                }),
                declaration: String::new(),
            };
            capability = capability.method(Method {
                name: method_name,
                arguments,
                response,
                result_envelope: true,
                declarations: declarations.clone(),
            });
        }
        capability
    }
}

pub trait IntoSpectaFunctions {
    fn into_specta_functions(
        self,
    ) -> Result<(Vec<FunctionDataType>, TypeDefs), specta::ExportError>;
}

impl IntoSpectaFunctions for (Vec<FunctionDataType>, TypeDefs) {
    fn into_specta_functions(
        self,
    ) -> Result<(Vec<FunctionDataType>, TypeDefs), specta::ExportError> {
        Ok(self)
    }
}

impl IntoSpectaFunctions for Result<(Vec<FunctionDataType>, TypeDefs), specta::ExportError> {
    fn into_specta_functions(
        self,
    ) -> Result<(Vec<FunctionDataType>, TypeDefs), specta::ExportError> {
        self
    }
}

#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct Bindings {
    capabilities: Vec<Capability>,
}

impl Bindings {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn capability(mut self, capability: Capability) -> Self {
        assert!(
            self.capabilities
                .iter()
                .all(|current| current.name != capability.name),
            "duplicate capability `{}`",
            capability.name
        );
        self.capabilities.push(capability);
        self
    }

    /// Render one deterministic module containing DTOs, raw Host augmentation,
    /// and typed JSON clients.
    pub fn render(&self) -> String {
        let mut output = String::from(HEADER);
        output.push_str("import type { Host } from \"@wabou/solid-renderer\";\n");
        output.push_str("import \"@wabou/solid-renderer\";\n\n");
        output.push_str("export type NativeResult<T> = T | PromiseLike<T>;\n\n");

        let declarations = self
            .capabilities
            .iter()
            .flat_map(|capability| &capability.methods)
            .flat_map(|method| &method.declarations)
            .map(|(name, declaration)| (name.clone(), declaration.clone()))
            .collect::<BTreeMap<_, _>>();
        for declaration in declarations.values() {
            output.push_str("export ");
            output.push_str(declaration.trim());
            output.push_str("\n\n");
        }

        output.push_str("declare module \"@wabou/solid-renderer\" {\n");
        output.push_str("  interface HostCapabilities {\n");
        for capability in sorted_capabilities(&self.capabilities) {
            output.push_str(&format!("    readonly {}: {{\n", capability.name));
            for method in sorted_methods(&capability.methods) {
                let parameter = method
                    .arguments
                    .iter()
                    .map(|argument| {
                        format!(
                            "{}: {}",
                            argument.name,
                            if argument.json {
                                "string"
                            } else {
                                &argument.ty.name
                            }
                        )
                    })
                    .collect::<Vec<_>>()
                    .join(", ");
                output.push_str(&format!(
                    "      {}({parameter}): NativeResult<string>;\n",
                    method.name,
                ));
            }
            output.push_str("    };\n");
        }
        output.push_str("  }\n}\n\n");

        if self
            .capabilities
            .iter()
            .flat_map(|capability| &capability.methods)
            .any(|method| method.result_envelope)
        {
            output.push_str(
                "function decodeNativeResult<T>(raw: string): T {\n  const result = JSON.parse(raw) as { ok: true; value: T } | { ok: false; error?: string };\n  if (!result.ok) throw new Error(result.error ?? \"Native capability failed\");\n  return result.value;\n}\n\n",
            );
        }

        for capability in sorted_capabilities(&self.capabilities) {
            let interface = format!("{}Client", upper_camel_case(&capability.name));
            output.push_str(&format!("export interface {interface} {{\n"));
            for method in sorted_methods(&capability.methods) {
                let parameter = method
                    .arguments
                    .iter()
                    .map(|argument| format!("{}: {}", argument.name, argument.ty.name))
                    .collect::<Vec<_>>()
                    .join(", ");
                output.push_str(&format!(
                    "  {}({parameter}): Promise<{}>;\n",
                    method.name, method.response.name
                ));
            }
            output.push_str("}\n\n");
            output.push_str(&format!(
                "export function create{interface}(host: Host): {interface} {{\n"
            ));
            output.push_str("  return {\n");
            for method in sorted_methods(&capability.methods) {
                let parameter = method
                    .arguments
                    .iter()
                    .map(|argument| argument.name.as_str())
                    .collect::<Vec<_>>()
                    .join(", ");
                let argument = method
                    .arguments
                    .iter()
                    .map(|argument| {
                        if argument.json {
                            format!("JSON.stringify({})", argument.name)
                        } else {
                            argument.name.clone()
                        }
                    })
                    .collect::<Vec<_>>()
                    .join(", ");
                let decode = if method.result_envelope {
                    format!(
                        "decodeNativeResult<{}>(await host.{}.{}({argument}))",
                        method.response.name, capability.name, method.name
                    )
                } else {
                    format!(
                        "JSON.parse(await host.{}.{}({argument})) as {}",
                        capability.name, method.name, method.response.name
                    )
                };
                output.push_str(&format!(
                    "    {}: async ({parameter}) => {decode},\n",
                    method.name,
                ));
            }
            output.push_str("  };\n}\n\n");
        }
        output.truncate(output.trim_end().len());
        output.push('\n');
        output
    }

    pub fn write(&self, path: impl AsRef<Path>) -> Result<(), BindingsError> {
        let path = path.as_ref();
        if let Some(parent) = path
            .parent()
            .filter(|parent| !parent.as_os_str().is_empty())
        {
            fs::create_dir_all(parent).map_err(|source| BindingsError::Io {
                path: parent.to_path_buf(),
                source,
            })?;
        }
        fs::write(path, self.render()).map_err(|source| BindingsError::Io {
            path: path.to_path_buf(),
            source,
        })
    }

    pub fn check(&self, path: impl AsRef<Path>) -> Result<(), BindingsError> {
        let path = path.as_ref();
        let actual = fs::read_to_string(path).map_err(|source| BindingsError::Io {
            path: path.to_path_buf(),
            source,
        })?;
        let expected = self.render();
        if actual == expected {
            Ok(())
        } else {
            Err(BindingsError::Drift(path.to_path_buf()))
        }
    }
}

#[derive(Debug)]
pub enum BindingsError {
    Io {
        path: PathBuf,
        source: std::io::Error,
    },
    Drift(PathBuf),
}

impl fmt::Display for BindingsError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Io { path, source } => {
                write!(formatter, "cannot access {}: {source}", path.display())
            }
            Self::Drift(path) => write!(
                formatter,
                "generated bindings differ from {}; run `wabou bindings write`",
                path.display()
            ),
        }
    }
}

impl std::error::Error for BindingsError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Io { source, .. } => Some(source),
            Self::Drift(_) => None,
        }
    }
}

#[derive(Default)]
struct DeclarationCollector {
    visited: BTreeSet<TypeId>,
    declarations: BTreeMap<String, String>,
}

impl DeclarationCollector {
    fn register<T: TS + 'static + ?Sized>(&mut self) -> TypeDeclaration {
        let config = Config::new().with_large_int("number");
        let declaration = TypeDeclaration {
            name: T::name(&config),
            declaration: T::decl(&config),
        };
        if self.visited.insert(TypeId::of::<T>()) {
            let identifier = T::ident(&config);
            if let Some(previous) = self
                .declarations
                .insert(identifier.clone(), declaration.declaration.clone())
            {
                assert_eq!(
                    previous, declaration.declaration,
                    "different Rust types export the same TypeScript name `{identifier}`"
                );
            }
            T::visit_dependencies(self);
        }
        declaration
    }
}

impl TypeVisitor for DeclarationCollector {
    fn visit<T: TS + 'static + ?Sized>(&mut self) {
        if T::output_path().is_some() {
            self.register::<T>();
        }
    }
}

fn sorted_capabilities(capabilities: &[Capability]) -> Vec<&Capability> {
    let mut values = capabilities.iter().collect::<Vec<_>>();
    values.sort_by(|left, right| left.name.cmp(&right.name));
    values
}

fn sorted_methods(methods: &[Method]) -> Vec<&Method> {
    let mut values = methods.iter().collect::<Vec<_>>();
    values.sort_by(|left, right| left.name.cmp(&right.name));
    values
}

fn assert_identifier(value: &str, kind: &str) {
    let mut chars = value.chars();
    let valid_start = chars
        .next()
        .is_some_and(|character| character == '_' || character.is_ascii_alphabetic());
    let valid_tail = chars.all(|character| character == '_' || character.is_ascii_alphanumeric());
    assert!(
        valid_start && valid_tail,
        "invalid {kind} identifier `{value}`"
    );
}

fn specta_config() -> ExportConfiguration {
    ExportConfiguration::new().bigint(BigIntExportBehavior::Number)
}

fn is_native_primitive(datatype: &DataType) -> bool {
    matches!(
        datatype,
        DataType::Primitive(
            PrimitiveType::String
                | PrimitiveType::char
                | PrimitiveType::bool
                | PrimitiveType::i8
                | PrimitiveType::i16
                | PrimitiveType::i32
                | PrimitiveType::i64
                | PrimitiveType::i128
                | PrimitiveType::isize
                | PrimitiveType::u8
                | PrimitiveType::u16
                | PrimitiveType::u32
                | PrimitiveType::u64
                | PrimitiveType::u128
                | PrimitiveType::usize
                | PrimitiveType::f32
                | PrimitiveType::f64
        )
    )
}

fn lower_camel_case(value: &str) -> String {
    let mut result = String::new();
    let mut uppercase = false;
    for character in value.chars() {
        if character == '_' || character == '-' {
            uppercase = true;
        } else if uppercase {
            result.extend(character.to_uppercase());
            uppercase = false;
        } else {
            result.push(character);
        }
    }
    result
}

fn upper_camel_case(value: &str) -> String {
    let mut result = String::new();
    let mut uppercase = true;
    for character in value.chars() {
        if character == '_' {
            uppercase = true;
        } else if uppercase {
            result.extend(character.to_uppercase());
            uppercase = false;
        } else {
            result.push(character);
        }
    }
    result
}

#[cfg(test)]
#[allow(dead_code)]
mod tests {
    use super::*;
    use serde::{Deserialize, Serialize};

    #[derive(TS)]
    struct Nested {
        value: String,
    }

    #[derive(TS)]
    struct Request {
        nested: Nested,
        count: u64,
    }

    #[derive(TS)]
    #[ts(rename_all = "camelCase")]
    enum Response {
        Accepted { display_name: String },
        Rejected,
    }

    #[derive(Deserialize, Type)]
    #[serde(rename_all = "camelCase")]
    struct FunctionRequest {
        display_name: String,
    }

    #[derive(Serialize, Type)]
    struct FunctionResponse {
        accepted: bool,
    }

    #[specta::specta]
    async fn update_file(id: String, request: FunctionRequest) -> Result<FunctionResponse, String> {
        let _ = (id, request);
        unreachable!()
    }

    fn fixture() -> Bindings {
        Bindings::new().capability(
            Capability::new("workspace")
                .method(Method::json::<Request, Response>("readFile"))
                .method(Method::json_result_no_args::<Response>("status")),
        )
    }

    #[test]
    fn renders_dependencies_raw_abi_and_typed_client() {
        let output = fixture().render();
        assert!(output.contains("export type Nested ="));
        assert!(output.contains("count: number"));
        assert!(output.contains("export type NativeResult<T> = T | PromiseLike<T>"));
        assert!(output.contains("readFile(request: string): NativeResult<string>"));
        assert!(output.contains("readFile(request: Request): Promise<Response>"));
        assert!(output.contains("JSON.stringify(request)"));
        assert!(output.contains("JSON.parse(await host.workspace.readFile"));
        assert!(output.contains("status(): NativeResult<string>"));
        assert!(output.contains("status(): Promise<Response>"));
        assert!(output.contains("decodeNativeResult<Response>(await host.workspace.status())"));
    }

    #[test]
    fn derives_methods_and_wire_encoding_from_rust_functions() {
        let output = Bindings::new()
            .capability(Capability::from_specta(
                "workspace",
                specta::functions::collect_types![update_file],
            ))
            .render();
        assert!(output.contains("export type FunctionRequest"));
        assert!(output.contains(
            "updateFile(id: string, request: FunctionRequest): Promise<FunctionResponse>"
        ));
        assert!(output.contains("host.workspace.updateFile(id, JSON.stringify(request))"));
    }

    #[test]
    fn check_reports_drift_without_rewriting_the_file() {
        let path = std::env::temp_dir().join(format!(
            "wabou-bindings-{}-{}.ts",
            std::process::id(),
            line!()
        ));
        fixture().write(&path).unwrap();
        fixture().check(&path).unwrap();
        fs::write(&path, "stale").unwrap();
        assert!(matches!(
            fixture().check(&path),
            Err(BindingsError::Drift(_))
        ));
        assert_eq!(fs::read_to_string(&path).unwrap(), "stale");
        fs::remove_file(path).unwrap();
    }
}
