//! Deterministic TypeScript clients and declarations for Wabou capabilities.
//!
//! A native QuickJS method may return immediately or through a Promise.
//! Generated clients normalize both forms to an asynchronous typed API and
//! own JSON serialization so application code only sees typed DTOs.

use std::collections::BTreeMap;
use std::fmt;
use std::fs;
use std::path::{Path, PathBuf};

use specta::functions::FunctionDataType;
use specta::ts::{self, BigIntExportBehavior, ExportConfiguration};
pub use specta::{self, Type};
use specta::{DataType, PrimitiveType, TypeDefs};

const HEADER: &str = "// AUTO-GENERATED by wabou-bindings. DO NOT EDIT.\n";

#[derive(Clone, Debug, Eq, PartialEq)]
struct TypeDeclaration {
    name: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct Argument {
    name: String,
    ty: TypeDeclaration,
    json: bool,
    optional: bool,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Method {
    name: String,
    arguments: Vec<Argument>,
    response: TypeDeclaration,
    result_envelope: bool,
    declarations: BTreeMap<String, String>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Capability {
    name: String,
    methods: Vec<Method>,
}

impl Capability {
    pub fn new(name: impl Into<String>) -> Self {
        let name = name.into();
        assert_identifier(&name, "capability");
        Self {
            name,
            methods: Vec::new(),
        }
    }

    fn method(mut self, method: Method) -> Self {
        assert!(
            self.methods
                .iter()
                .all(|current| current.name != method.name),
            "duplicate method `{}` in capability `{}`",
            method.name,
            self.name
        );
        self.methods.push(method);
        self
    }

    /// Build a capability directly from Rust functions annotated with
    /// `#[specta::specta]`. Function arguments and return DTOs become the
    /// typed client API; primitive arguments cross the native ABI directly
    /// while structured arguments are JSON encoded.
    pub fn from_specta(name: impl Into<String>, contract: impl IntoSpectaFunctions) -> Self {
        let (functions, type_defs) = contract
            .into_specta_functions()
            .unwrap_or_else(|error| panic!("invalid Specta function contract: {error}"));
        let mut capability = Self::new(name);
        let config = specta_config();
        let declarations = specta_declarations(&type_defs);

        for function in functions {
            let method_name = lower_camel_case(function.name);
            let arguments = function
                .args
                .into_iter()
                .map(|(name, datatype)| Argument {
                    name: lower_camel_case(name),
                    ty: TypeDeclaration {
                        name: ts::datatype(&config, &datatype).unwrap_or_else(|error| {
                            panic!("cannot export argument `{name}`: {error}")
                        }),
                    },
                    json: !is_native_primitive(&datatype),
                    optional: matches!(datatype, DataType::Nullable(_)),
                })
                .collect();
            let response = TypeDeclaration {
                name: ts::datatype(&config, &function.result).unwrap_or_else(|error| {
                    panic!("cannot export result of `{}`: {error}", function.name)
                }),
            };
            capability = capability.method(Method {
                name: method_name,
                arguments,
                response,
                result_envelope: true,
                declarations: declarations.clone(),
            });
        }
        capability
    }
}

pub trait IntoSpectaFunctions {
    fn into_specta_functions(
        self,
    ) -> Result<(Vec<FunctionDataType>, TypeDefs), specta::ExportError>;
}

impl IntoSpectaFunctions for (Vec<FunctionDataType>, TypeDefs) {
    fn into_specta_functions(
        self,
    ) -> Result<(Vec<FunctionDataType>, TypeDefs), specta::ExportError> {
        Ok(self)
    }
}

impl IntoSpectaFunctions for Result<(Vec<FunctionDataType>, TypeDefs), specta::ExportError> {
    fn into_specta_functions(
        self,
    ) -> Result<(Vec<FunctionDataType>, TypeDefs), specta::ExportError> {
        self
    }
}

#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct Bindings {
    capabilities: Vec<Capability>,
}

/// A generated TypeScript interface for a flat native module. Unlike a
/// capability client this preserves each Rust function's sync/async shape and
/// does not impose Wabou's JSON result envelope.
pub struct FunctionModule {
    name: String,
    functions: Vec<FunctionDataType>,
    declarations: BTreeMap<String, String>,
}

impl FunctionModule {
    pub fn from_specta(name: impl Into<String>, contract: impl IntoSpectaFunctions) -> Self {
        let name = name.into();
        assert_identifier(&name, "interface");
        let (functions, type_defs) = contract
            .into_specta_functions()
            .unwrap_or_else(|error| panic!("invalid Specta function contract: {error}"));
        Self {
            name,
            functions,
            declarations: specta_declarations(&type_defs),
        }
    }

    pub fn render(&self) -> String {
        let config = specta_config();
        let mut output = String::from(HEADER);
        for declaration in self.declarations.values() {
            output.push_str("export ");
            output.push_str(declaration.trim());
            output.push_str("\n\n");
        }
        output.push_str(&format!("export interface {} {{\n", self.name));
        let mut functions = self.functions.iter().collect::<Vec<_>>();
        functions.sort_by_key(|function| function.name);
        for function in functions {
            let arguments = function
                .args
                .iter()
                .map(|(name, datatype)| {
                    let optional = matches!(datatype, DataType::Nullable(_));
                    let ty = ts::datatype(&config, datatype)
                        .unwrap_or_else(|error| panic!("cannot export argument `{name}`: {error}"));
                    format!(
                        "{}{}: {ty}",
                        lower_camel_case(name),
                        if optional { "?" } else { "" }
                    )
                })
                .collect::<Vec<_>>()
                .join(", ");
            let result = ts::datatype(&config, &function.result).unwrap_or_else(|error| {
                panic!("cannot export result of `{}`: {error}", function.name)
            });
            output.push_str(&format!(
                "  {}({arguments}): {};\n",
                lower_camel_case(function.name),
                if function.asyncness {
                    format!("Promise<{result}>")
                } else {
                    result
                }
            ));
        }
        output.push_str("}\n");
        output
    }

    pub fn write(&self, path: impl AsRef<Path>) -> Result<(), BindingsError> {
        write_generated(path.as_ref(), self.render())
    }

    pub fn check(&self, path: impl AsRef<Path>) -> Result<(), BindingsError> {
        check_generated(path.as_ref(), self.render())
    }
}

impl Bindings {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn capability(mut self, capability: Capability) -> Self {
        assert!(
            self.capabilities
                .iter()
                .all(|current| current.name != capability.name),
            "duplicate capability `{}`",
            capability.name
        );
        self.capabilities.push(capability);
        self
    }

    /// Render one deterministic module containing DTOs, a module-local native
    /// capability contract, and typed JSON clients.
    pub fn render(&self) -> String {
        let mut output = String::from(HEADER);
        output.push_str("import type { Host } from \"@wabou/core\";\n");
        output.push_str("import \"@wabou/core\";\n\n");
        output.push_str("export type NativeResult<T> = T | PromiseLike<T>;\n\n");

        let declarations = self
            .capabilities
            .iter()
            .flat_map(|capability| &capability.methods)
            .flat_map(|method| &method.declarations)
            .map(|(name, declaration)| (name.clone(), declaration.clone()))
            .collect::<BTreeMap<_, _>>();
        for declaration in declarations.values() {
            output.push_str("export ");
            output.push_str(declaration.trim());
            output.push_str("\n\n");
        }

        output.push_str("interface NativeHostCapabilities {\n");
        for capability in sorted_capabilities(&self.capabilities) {
            output.push_str(&format!("  readonly {}: {{\n", capability.name));
            for method in sorted_methods(&capability.methods) {
                let parameter = method
                    .arguments
                    .iter()
                    .map(|argument| {
                        format!(
                            "{}: {}",
                            if argument.optional {
                                format!("{}?", argument.name)
                            } else {
                                argument.name.clone()
                            },
                            if argument.json {
                                "string"
                            } else {
                                &argument.ty.name
                            }
                        )
                    })
                    .collect::<Vec<_>>()
                    .join(", ");
                output.push_str(&format!(
                    "    {}({parameter}): NativeResult<string>;\n",
                    method.name,
                ));
            }
            output.push_str("  };\n");
        }
        output.push_str("}\n\n");

        if self
            .capabilities
            .iter()
            .flat_map(|capability| &capability.methods)
            .any(|method| method.result_envelope)
        {
            output.push_str(
                "function decodeNativeResult<T>(raw: string): T {\n  const result = JSON.parse(raw) as { ok: true; value: T } | { ok: false; error?: string };\n  if (!result.ok) throw new Error(result.error ?? \"Native capability failed\");\n  return result.value;\n}\n\n",
            );
        }

        for capability in sorted_capabilities(&self.capabilities) {
            let interface = format!("{}Client", upper_camel_case(&capability.name));
            output.push_str(&format!("export interface {interface} {{\n"));
            for method in sorted_methods(&capability.methods) {
                let parameter = method
                    .arguments
                    .iter()
                    .map(|argument| {
                        format!(
                            "{}{}: {}",
                            argument.name,
                            if argument.optional { "?" } else { "" },
                            argument.ty.name
                        )
                    })
                    .collect::<Vec<_>>()
                    .join(", ");
                output.push_str(&format!(
                    "  {}({parameter}): Promise<{}>;\n",
                    method.name, method.response.name
                ));
            }
            output.push_str("}\n\n");
            output.push_str(&format!(
                "export function create{interface}(host: Host): {interface} {{\n"
            ));
            output.push_str("  const nativeHost = host as Host & NativeHostCapabilities;\n");
            output.push_str("  return {\n");
            for method in sorted_methods(&capability.methods) {
                let parameter = method
                    .arguments
                    .iter()
                    .map(|argument| argument.name.as_str())
                    .collect::<Vec<_>>()
                    .join(", ");
                let argument = method
                    .arguments
                    .iter()
                    .map(|argument| {
                        if argument.json {
                            format!("JSON.stringify({})", argument.name)
                        } else {
                            argument.name.clone()
                        }
                    })
                    .collect::<Vec<_>>()
                    .join(", ");
                let decode = if method.result_envelope {
                    format!(
                        "decodeNativeResult<{}>(await nativeHost.{}.{}({argument}))",
                        method.response.name, capability.name, method.name
                    )
                } else {
                    format!(
                        "JSON.parse(await nativeHost.{}.{}({argument})) as {}",
                        capability.name, method.name, method.response.name
                    )
                };
                output.push_str(&format!(
                    "    {}: async ({parameter}) => {decode},\n",
                    method.name,
                ));
            }
            output.push_str("  };\n}\n\n");
        }
        output.truncate(output.trim_end().len());
        output.push('\n');
        output
    }

    pub fn write(&self, path: impl AsRef<Path>) -> Result<(), BindingsError> {
        write_generated(path.as_ref(), self.render())
    }

    pub fn check(&self, path: impl AsRef<Path>) -> Result<(), BindingsError> {
        check_generated(path.as_ref(), self.render())
    }
}

fn write_generated(path: &Path, output: String) -> Result<(), BindingsError> {
    if let Some(parent) = path
        .parent()
        .filter(|parent| !parent.as_os_str().is_empty())
    {
        fs::create_dir_all(parent).map_err(|source| BindingsError::Io {
            path: parent.to_path_buf(),
            source,
        })?;
    }
    fs::write(path, output).map_err(|source| BindingsError::Io {
        path: path.to_path_buf(),
        source,
    })
}

fn check_generated(path: &Path, expected: String) -> Result<(), BindingsError> {
    let actual = fs::read_to_string(path).map_err(|source| BindingsError::Io {
        path: path.to_path_buf(),
        source,
    })?;
    if actual == expected {
        Ok(())
    } else {
        Err(BindingsError::Drift(path.to_path_buf()))
    }
}

#[derive(Debug)]
pub enum BindingsError {
    Io {
        path: PathBuf,
        source: std::io::Error,
    },
    Drift(PathBuf),
}

impl fmt::Display for BindingsError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Io { path, source } => {
                write!(formatter, "cannot access {}: {source}", path.display())
            }
            Self::Drift(path) => write!(
                formatter,
                "generated bindings differ from {}; run `wabou bindings write`",
                path.display()
            ),
        }
    }
}

impl std::error::Error for BindingsError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Io { source, .. } => Some(source),
            Self::Drift(_) => None,
        }
    }
}

fn sorted_capabilities(capabilities: &[Capability]) -> Vec<&Capability> {
    let mut values = capabilities.iter().collect::<Vec<_>>();
    values.sort_by(|left, right| left.name.cmp(&right.name));
    values
}

fn sorted_methods(methods: &[Method]) -> Vec<&Method> {
    let mut values = methods.iter().collect::<Vec<_>>();
    values.sort_by(|left, right| left.name.cmp(&right.name));
    values
}

fn assert_identifier(value: &str, kind: &str) {
    let mut chars = value.chars();
    let valid_start = chars
        .next()
        .is_some_and(|character| character == '_' || character.is_ascii_alphabetic());
    let valid_tail = chars.all(|character| character == '_' || character.is_ascii_alphanumeric());
    assert!(
        valid_start && valid_tail,
        "invalid {kind} identifier `{value}`"
    );
}

fn specta_config() -> ExportConfiguration {
    ExportConfiguration::new().bigint(BigIntExportBehavior::Number)
}

fn specta_declarations(type_defs: &TypeDefs) -> BTreeMap<String, String> {
    let config = specta_config();
    type_defs
        .values()
        .filter_map(Option::as_ref)
        .map(|datatype| {
            let declaration = ts::export_datatype(&config, datatype)
                .unwrap_or_else(|error| panic!("cannot export `{}`: {error}", datatype.name));
            (
                datatype.name.to_string(),
                declaration.replacen("export type", "type", 1),
            )
        })
        .collect()
}

fn is_native_primitive(datatype: &DataType) -> bool {
    if let DataType::Nullable(inner) = datatype {
        return is_native_primitive(inner);
    }
    matches!(
        datatype,
        DataType::Primitive(
            PrimitiveType::String
                | PrimitiveType::char
                | PrimitiveType::bool
                | PrimitiveType::i8
                | PrimitiveType::i16
                | PrimitiveType::i32
                | PrimitiveType::i64
                | PrimitiveType::i128
                | PrimitiveType::isize
                | PrimitiveType::u8
                | PrimitiveType::u16
                | PrimitiveType::u32
                | PrimitiveType::u64
                | PrimitiveType::u128
                | PrimitiveType::usize
                | PrimitiveType::f32
                | PrimitiveType::f64
        )
    )
}

fn lower_camel_case(value: &str) -> String {
    let mut result = String::new();
    let mut uppercase = false;
    for character in value.chars() {
        if character == '_' || character == '-' {
            uppercase = true;
        } else if uppercase {
            result.extend(character.to_uppercase());
            uppercase = false;
        } else {
            result.push(character);
        }
    }
    result
}

fn upper_camel_case(value: &str) -> String {
    let mut result = String::new();
    let mut uppercase = true;
    for character in value.chars() {
        if character == '_' {
            uppercase = true;
        } else if uppercase {
            result.extend(character.to_uppercase());
            uppercase = false;
        } else {
            result.push(character);
        }
    }
    result
}

#[cfg(test)]
#[allow(dead_code)]
mod tests {
    use super::*;
    use serde::{Deserialize, Serialize};

    #[derive(Deserialize, Type)]
    #[serde(rename_all = "camelCase")]
    struct FunctionRequest {
        display_name: String,
    }

    #[derive(Serialize, Type)]
    struct FunctionResponse {
        accepted: bool,
    }

    #[specta::specta]
    async fn update_file(id: String, request: FunctionRequest) -> Result<FunctionResponse, String> {
        let _ = (id, request);
        unreachable!()
    }

    #[specta::specta]
    fn current_status() -> FunctionResponse {
        unreachable!()
    }

    fn fixture() -> Bindings {
        Bindings::new().capability(Capability::from_specta(
            "workspace",
            specta::functions::collect_types![update_file],
        ))
    }

    #[test]
    fn renders_dependencies_raw_abi_and_typed_client() {
        let output = fixture().render();
        assert!(output.contains("export type FunctionRequest ="));
        assert!(output.contains("displayName: string"));
        assert!(output.contains("export type NativeResult<T> = T | PromiseLike<T>"));
        assert!(output.contains("interface NativeHostCapabilities"));
        assert!(!output.contains("@wabou/solid-renderer"));
        assert!(output.contains("updateFile(id: string, request: string): NativeResult<string>"));
        assert!(output.contains(
            "updateFile(id: string, request: FunctionRequest): Promise<FunctionResponse>"
        ));
        assert!(output.contains("JSON.stringify(request)"));
        assert!(output.contains(
            "decodeNativeResult<FunctionResponse>(await nativeHost.workspace.updateFile"
        ));
    }

    #[test]
    fn derives_methods_and_wire_encoding_from_rust_functions() {
        let output = Bindings::new()
            .capability(Capability::from_specta(
                "workspace",
                specta::functions::collect_types![update_file],
            ))
            .render();
        assert!(output.contains("export type FunctionRequest"));
        assert!(output.contains(
            "updateFile(id: string, request: FunctionRequest): Promise<FunctionResponse>"
        ));
        assert!(output.contains("nativeHost.workspace.updateFile(id, JSON.stringify(request))"));
    }

    #[test]
    fn flat_function_modules_preserve_synchronous_signatures() {
        let output = FunctionModule::from_specta(
            "NativeFiles",
            specta::functions::collect_types![update_file, current_status],
        )
        .render();
        assert!(output.contains("export interface NativeFiles"));
        assert!(output.contains(
            "updateFile(id: string, request: FunctionRequest): Promise<FunctionResponse>"
        ));
        assert!(output.contains("currentStatus(): FunctionResponse"));
    }

    #[test]
    fn check_reports_drift_without_rewriting_the_file() {
        let path = std::env::temp_dir().join(format!(
            "wabou-bindings-{}-{}.ts",
            std::process::id(),
            line!()
        ));
        fixture().write(&path).unwrap();
        fixture().check(&path).unwrap();
        fs::write(&path, "stale").unwrap();
        assert!(matches!(
            fixture().check(&path),
            Err(BindingsError::Drift(_))
        ));
        assert_eq!(fs::read_to_string(&path).unwrap(), "stale");
        fs::remove_file(path).unwrap();
    }
}
