[package]
name = "wabou-bindgen"
version.workspace = true
edition = "2024"
license.workspace = true

[dependencies]
serde = { workspace = true }
specta = { workspace = true, optional = true }
specta-serde = { workspace = true, optional = true }
specta-typescript = { workspace = true, optional = true }

[features]
default = ["generate"]
generate = [
  "dep:specta",
  "dep:specta-serde",
  "dep:specta-typescript",
]

[dev-dependencies]
serde = { workspace = true, features = ["derive"] }
