[package]
name = "wabou-style"
version.workspace = true
edition = "2024"
license.workspace = true

[dependencies]
bon = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
winnow = "1.0.4"

[[bin]]
name = "wabou-style-manifest"
path = "src/bin/manifest.rs"
