[package]
name = "wabou-native-capability-experiment"
version = "0.0.0"
edition = "2024"
publish = false
license = "Apache-2.0"

[dependencies]
rquickjs = { version = "0.12.1", features = ["full-async", "rust-alloc"] }
rquickjs-serde = "0.6.1"
serde = { version = "1", features = ["derive"] }

[workspace]
