//! Deterministic TypeScript clients and declarations for Wabou capabilities.
//!
//! A native QuickJS method may return immediately or through a Promise.
//! Generated clients normalize both forms to an asynchronous typed API and
//! own JSON serialization so application code only sees typed DTOs.
//!
//! The default `generate` feature exposes Specta-backed TypeScript generation.
//! Runtime crates may disable it and retain only [`JsonMethod`] plus the shared
//! contract identifier validation, without pulling a language exporter into
//! the application runtime graph.

#![warn(missing_docs)]

use std::marker::PhantomData;

use serde::{Serialize, de::DeserializeOwned};
#[cfg(feature = "generate")]
pub use specta::{self, Type};
#[cfg(feature = "generate")]
use specta::{Format, Types, datatype::DataType};
#[cfg(feature = "generate")]
use specta_typescript::{Typescript, primitives};
#[cfg(feature = "generate")]
use std::collections::{BTreeMap, BTreeSet};
#[cfg(feature = "generate")]
use std::fmt;
#[cfg(feature = "generate")]
use std::fs;
#[cfg(feature = "generate")]
use std::path::{Path, PathBuf};

#[cfg(feature = "generate")]
const HEADER: &str = "// AUTO-GENERATED by wabou-bindgen. DO NOT EDIT.\n";

/// One typed JSON capability method shared by binding generation and runtime
/// registration.
///
/// The value is zero-sized apart from its static wire name. Its generic types
/// make request/response drift a Rust compile error rather than a runtime
/// bridge failure.
pub struct JsonMethod<Request, Response> {
    name: &'static str,
    #[cfg_attr(not(feature = "generate"), allow(dead_code))]
    has_request: bool,
    marker: PhantomData<fn(Request) -> Response>,
}

impl<Request, Response> Copy for JsonMethod<Request, Response> {}

impl<Request, Response> Clone for JsonMethod<Request, Response> {
    fn clone(&self) -> Self {
        *self
    }
}

impl<Request, Response> JsonMethod<Request, Response> {
    /// Define a method accepting one JSON request value.
    ///
    /// The directional serde bounds match the runtime wire contract: requests
    /// are decoded by Rust and responses are encoded for JavaScript.
    ///
    /// A schema-only request cannot accidentally become a wire contract:
    ///
    /// ```compile_fail
    /// use wabou_bindgen::JsonMethod;
    ///
    /// struct NotDeserializable;
    /// const INVALID: JsonMethod<NotDeserializable, bool> =
    ///     JsonMethod::new("invalid");
    /// ```
    pub const fn new(name: &'static str) -> Self
    where
        Request: DeserializeOwned,
        Response: Serialize,
    {
        Self {
            name,
            has_request: true,
            marker: PhantomData,
        }
    }

    /// Return the native wire name.
    pub const fn name(self) -> &'static str {
        self.name
    }

    /// Return whether the wire method accepts a JSON request argument.
    ///
    /// This keeps runtime registration and generated clients aligned for
    /// [`JsonMethod::no_request`], whose native function truly has no
    /// argument instead of accepting an undocumented JSON `null` sentinel.
    pub const fn has_request(self) -> bool {
        self.has_request
    }
}

impl<Response> JsonMethod<(), Response> {
    /// Define a method whose public client accepts no request value.
    pub const fn no_request(name: &'static str) -> Self
    where
        Response: Serialize,
    {
        Self {
            name,
            has_request: false,
            marker: PhantomData,
        }
    }
}

/// One typed function in a flat native interface.
#[cfg(feature = "generate")]
pub struct NativeMethod<Arguments, Response> {
    name: &'static str,
    argument_names: &'static [&'static str],
    asyncness: bool,
    marker: PhantomData<fn(Arguments) -> Response>,
}

#[cfg(feature = "generate")]
impl<Arguments, Response> Copy for NativeMethod<Arguments, Response> {}

#[cfg(feature = "generate")]
impl<Arguments, Response> Clone for NativeMethod<Arguments, Response> {
    fn clone(&self) -> Self {
        *self
    }
}

#[cfg(feature = "generate")]
impl<Arguments, Response> NativeMethod<Arguments, Response> {
    /// Define a synchronous native method. `Arguments` must be a Rust tuple;
    /// `argument_names` must contain one name per tuple field.
    pub const fn sync(name: &'static str, argument_names: &'static [&'static str]) -> Self {
        Self {
            name,
            argument_names,
            asyncness: false,
            marker: PhantomData,
        }
    }

    /// Define an asynchronous native method.
    pub const fn asynchronous(name: &'static str, argument_names: &'static [&'static str]) -> Self {
        Self {
            name,
            argument_names,
            asyncness: true,
            marker: PhantomData,
        }
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
#[cfg(feature = "generate")]
struct Argument {
    name: String,
    ty: String,
}

#[cfg(feature = "generate")]
impl Argument {
    fn typed_parameter(&self) -> String {
        format!("{}: {}", self.name, self.ty)
    }

    fn native_parameter(&self) -> String {
        format!("{}: string", self.name)
    }

    fn native_value(&self) -> String {
        format!("JSON.stringify({})", self.name)
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
/// One generated capability method and its DTO declarations.
#[cfg(feature = "generate")]
pub struct Method {
    name: String,
    arguments: Vec<Argument>,
    response: String,
    declarations: BTreeMap<String, String>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
/// Named group of native functions exposed as one TypeScript client.
#[cfg(feature = "generate")]
pub struct Capability {
    name: String,
    methods: Vec<Method>,
}

#[cfg(feature = "generate")]
impl Capability {
    /// Construct an empty capability with a valid TypeScript identifier.
    pub fn new(name: impl Into<String>) -> Self {
        let name = name.into();
        assert_identifier(&name, "capability");
        Self {
            name,
            methods: Vec::new(),
        }
    }

    fn push_method(mut self, method: Method) -> Self {
        assert!(
            self.methods
                .iter()
                .all(|current| current.name != method.name),
            "duplicate method `{}` in capability `{}`",
            method.name,
            self.name
        );
        self.methods.push(method);
        self
    }

    /// Add a typed method contract shared with runtime registration.
    pub fn method<Request: Type, Response: Type>(
        self,
        method: JsonMethod<Request, Response>,
    ) -> Self {
        assert_identifier(method.name, "method");
        let mut request_types = Types::default();
        let request = Request::definition(&mut request_types);
        let mut response_types = Types::default();
        let response = Response::definition(&mut response_types);
        let mut declarations = BTreeMap::new();
        if method.has_request {
            merge_declarations(
                &mut declarations,
                specta_declarations(&request_types, specta_serde::Phase::Deserialize),
            );
        }
        merge_declarations(
            &mut declarations,
            specta_declarations(&response_types, specta_serde::Phase::Serialize),
        );
        self.push_method(Method {
            name: method.name.to_owned(),
            arguments: method
                .has_request
                .then_some(Argument {
                    name: "request".to_owned(),
                    ty: render_datatype(
                        &request_types,
                        &request,
                        specta_serde::Phase::Deserialize,
                        "request",
                    ),
                })
                .into_iter()
                .collect(),
            response: render_datatype(
                &response_types,
                &response,
                specta_serde::Phase::Serialize,
                "response",
            ),
            declarations,
        })
    }
}

#[derive(Clone, Debug, Default, Eq, PartialEq)]
/// Deterministic collection of generated capability clients.
#[cfg(feature = "generate")]
pub struct Bindings {
    capabilities: Vec<Capability>,
}

/// A generated TypeScript interface for a flat native module. Unlike a
/// capability client this preserves each Rust function's sync/async shape and
/// does not impose Wabou's JSON result envelope.
#[cfg(feature = "generate")]
pub struct FunctionModule {
    name: String,
    functions: Vec<FunctionSignature>,
    declarations: BTreeMap<String, String>,
}

#[cfg(feature = "generate")]
struct FunctionSignature {
    name: String,
    arguments: Vec<(String, String)>,
    response: String,
    asyncness: bool,
}

#[cfg(feature = "generate")]
impl FunctionModule {
    /// Construct an empty flat native module.
    pub fn new(name: impl Into<String>) -> Self {
        let name = name.into();
        assert_identifier(&name, "interface");
        Self {
            name,
            functions: Vec::new(),
            declarations: BTreeMap::new(),
        }
    }

    /// Add a typed native method.
    pub fn method<Arguments: Type, Response: Type>(
        mut self,
        method: NativeMethod<Arguments, Response>,
    ) -> Self {
        assert_identifier(method.name, "method");
        assert!(
            self.functions
                .iter()
                .all(|current| current.name != method.name),
            "duplicate method `{}` in interface `{}`",
            method.name,
            self.name
        );
        let mut argument_types = Types::default();
        let arguments = Arguments::definition(&mut argument_types);
        let mut response_types = Types::default();
        let response = Response::definition(&mut response_types);
        let DataType::Tuple(arguments) = arguments else {
            panic!(
                "native method `{}` arguments must be a Rust tuple",
                method.name
            );
        };
        assert_eq!(
            arguments.elements.len(),
            method.argument_names.len(),
            "native method `{}` has {} argument types but {} names",
            method.name,
            arguments.elements.len(),
            method.argument_names.len()
        );
        merge_declarations(
            &mut self.declarations,
            specta_declarations(&argument_types, specta_serde::Phase::Deserialize),
        );
        merge_declarations(
            &mut self.declarations,
            specta_declarations(&response_types, specta_serde::Phase::Serialize),
        );
        self.functions.push(FunctionSignature {
            name: method.name.to_owned(),
            arguments: method
                .argument_names
                .iter()
                .zip(arguments.elements)
                .map(|(name, datatype)| {
                    (
                        (*name).to_owned(),
                        render_datatype(
                            &argument_types,
                            &datatype,
                            specta_serde::Phase::Deserialize,
                            "argument",
                        ),
                    )
                })
                .collect(),
            response: render_datatype(
                &response_types,
                &response,
                specta_serde::Phase::Serialize,
                "response",
            ),
            asyncness: method.asyncness,
        });
        self
    }

    /// Render deterministic TypeScript declarations for the native interface.
    pub fn render(&self) -> String {
        let mut output = String::from(HEADER);
        push_declarations(&mut output, &self.declarations);
        output.push_str(&format!("export interface {} {{\n", self.name));
        let mut functions = self.functions.iter().collect::<Vec<_>>();
        functions.sort_by(|left, right| left.name.cmp(&right.name));
        for function in functions {
            let arguments = function
                .arguments
                .iter()
                .map(|(name, ty)| format!("{name}: {ty}"))
                .collect::<Vec<_>>()
                .join(", ");
            let result = &function.response;
            output.push_str(&format!(
                "  {}({arguments}): {};\n",
                function.name,
                if function.asyncness {
                    format!("Promise<{result}>")
                } else {
                    result.to_owned()
                }
            ));
        }
        output.push_str("}\n");
        output
    }

    /// Render and write the generated module, creating parent directories.
    pub fn write(&self, path: impl AsRef<Path>) -> Result<(), BindingsError> {
        write_generated(path.as_ref(), self.render())
    }

    /// Verify that an existing generated module exactly matches current output.
    pub fn check(&self, path: impl AsRef<Path>) -> Result<(), BindingsError> {
        check_generated(path.as_ref(), self.render())
    }
}

#[cfg(feature = "generate")]
impl Bindings {
    /// Construct an empty capability collection.
    pub fn new() -> Self {
        Self::default()
    }

    /// Add a uniquely named capability.
    pub fn capability(mut self, capability: Capability) -> Self {
        assert!(
            self.capabilities
                .iter()
                .all(|current| current.name != capability.name),
            "duplicate capability `{}`",
            capability.name
        );
        self.capabilities.push(capability);
        self
    }

    /// Render one deterministic module containing DTOs, a module-local native
    /// capability contract, and typed JSON clients.
    pub fn render(&self) -> String {
        let mut output = String::from(HEADER);
        output.push_str("import { type Host, useHost } from \"@wabou/core\";\n\n");
        output.push_str("export type NativeResult<T> = T | PromiseLike<T>;\n\n");

        let mut declarations = BTreeMap::new();
        for method in self
            .capabilities
            .iter()
            .flat_map(|capability| &capability.methods)
        {
            merge_declarations(&mut declarations, method.declarations.clone());
        }
        push_declarations(&mut output, &declarations);

        output.push_str("interface NativeHostCapabilities {\n");
        for capability in sorted_capabilities(&self.capabilities) {
            output.push_str(&format!("  readonly {}: {{\n", capability.name));
            for method in sorted_methods(&capability.methods) {
                let parameter = native_parameters(method);
                output.push_str(&format!(
                    "    {}({parameter}): NativeResult<string>;\n",
                    method.name,
                ));
            }
            output.push_str("  };\n");
        }
        output.push_str("}\n\n");

        if self
            .capabilities
            .iter()
            .any(|capability| !capability.methods.is_empty())
        {
            output.push_str(
                "export class NativeCapabilityError extends Error {\n  readonly operation: string;\n\n  constructor(operation: string, message: string) {\n    super(`${operation}: ${message}`);\n    this.name = \"NativeCapabilityError\";\n    this.operation = operation;\n  }\n}\n\nfunction decodeNativeResult<T>(raw: string, operation: string): T {\n  let result: unknown;\n  try {\n    result = JSON.parse(raw);\n  } catch (error) {\n    const detail = error instanceof Error ? error.message : String(error);\n    throw new NativeCapabilityError(operation, `invalid JSON response: ${detail}`);\n  }\n  if (typeof result !== \"object\" || result === null || typeof (result as { ok?: unknown }).ok !== \"boolean\") {\n    throw new NativeCapabilityError(operation, \"invalid response envelope\");\n  }\n  const envelope = result as { ok: true; value?: T } | { ok: false; error?: unknown };\n  if (!envelope.ok) {\n    const detail = typeof envelope.error === \"string\" ? envelope.error : \"native capability failed\";\n    throw new NativeCapabilityError(operation, detail);\n  }\n  if (!(\"value\" in envelope)) {\n    throw new NativeCapabilityError(operation, \"successful response is missing `value`\");\n  }\n  return envelope.value as T;\n}\n\n",
            );
        }

        for capability in sorted_capabilities(&self.capabilities) {
            let interface = format!("{}Client", upper_camel_case(&capability.name));
            output.push_str(&format!("export interface {interface} {{\n"));
            for method in sorted_methods(&capability.methods) {
                let parameter = join_arguments(method, Argument::typed_parameter);
                output.push_str(&format!(
                    "  {}({parameter}): Promise<{}>;\n",
                    method.name, method.response
                ));
            }
            output.push_str("}\n\n");
            output.push_str(&format!(
                "export function create{interface}(host: Host): {interface} {{\n"
            ));
            output.push_str("  const nativeHost = host as Host & NativeHostCapabilities;\n");
            output.push_str("  return {\n");
            for method in sorted_methods(&capability.methods) {
                let parameter = method
                    .arguments
                    .iter()
                    .map(|argument| argument.name.as_str())
                    .collect::<Vec<_>>()
                    .join(", ");
                let argument = native_arguments(method);
                let decode = format!(
                    "decodeNativeResult<{}>(await nativeHost.{}.{}({argument}), \"{}.{}\")",
                    method.response, capability.name, method.name, capability.name, method.name
                );
                output.push_str(&format!(
                    "    {}: async ({parameter}) => {decode},\n",
                    method.name,
                ));
            }
            output.push_str("  };\n}\n\n");
            output.push_str(&format!(
                "export function use{interface}(): {interface} {{\n  return create{interface}(useHost());\n}}\n\n"
            ));
        }
        output.truncate(output.trim_end().len());
        output.push('\n');
        output
    }

    /// Render and write all clients, creating parent directories.
    pub fn write(&self, path: impl AsRef<Path>) -> Result<(), BindingsError> {
        write_generated(path.as_ref(), self.render())
    }

    /// Verify that existing generated clients exactly match current output.
    pub fn check(&self, path: impl AsRef<Path>) -> Result<(), BindingsError> {
        check_generated(path.as_ref(), self.render())
    }
}

#[cfg(feature = "generate")]
fn push_declarations(output: &mut String, declarations: &BTreeMap<String, String>) {
    for declaration in declarations.values() {
        output.push_str("export ");
        output.push_str(declaration.trim());
        output.push_str("\n\n");
    }

    let mut aliases = BTreeMap::new();
    for name in declarations.keys() {
        let Some((base, opposite)) = name
            .strip_suffix("_Serialize")
            .map(|base| (base, format!("{base}_Deserialize")))
            .or_else(|| {
                name.strip_suffix("_Deserialize")
                    .map(|base| (base, format!("{base}_Serialize")))
            })
        else {
            continue;
        };
        if !declarations.contains_key(base) && !declarations.contains_key(&opposite) {
            aliases.insert(base, name);
        }
    }
    for (alias, target) in aliases {
        output.push_str(&format!("export type {alias} = {target};\n\n"));
    }
}

#[cfg(feature = "generate")]
fn merge_declarations(
    target: &mut BTreeMap<String, String>,
    declarations: BTreeMap<String, String>,
) {
    for (name, declaration) in declarations {
        merge_declaration(target, name, declaration);
    }
}

#[cfg(feature = "generate")]
fn merge_declaration(target: &mut BTreeMap<String, String>, name: String, declaration: String) {
    match target.entry(name) {
        std::collections::btree_map::Entry::Vacant(entry) => {
            entry.insert(declaration);
        }
        std::collections::btree_map::Entry::Occupied(entry) => assert_eq!(
            entry.get(),
            &declaration,
            "conflicting TypeScript declaration for `{}`; bridge DTO names must be unique within one generated module",
            entry.key()
        ),
    }
}

#[cfg(feature = "generate")]
fn join_arguments(method: &Method, render: fn(&Argument) -> String) -> String {
    method
        .arguments
        .iter()
        .map(render)
        .collect::<Vec<_>>()
        .join(", ")
}

#[cfg(feature = "generate")]
fn native_parameters(method: &Method) -> String {
    join_arguments(method, Argument::native_parameter)
}

#[cfg(feature = "generate")]
fn native_arguments(method: &Method) -> String {
    join_arguments(method, Argument::native_value)
}

#[cfg(feature = "generate")]
fn write_generated(path: &Path, output: String) -> Result<(), BindingsError> {
    if let Some(parent) = path
        .parent()
        .filter(|parent| !parent.as_os_str().is_empty())
    {
        fs::create_dir_all(parent).map_err(|source| BindingsError::Io {
            path: parent.to_path_buf(),
            source,
        })?;
    }
    fs::write(path, output).map_err(|source| BindingsError::Io {
        path: path.to_path_buf(),
        source,
    })
}

#[cfg(feature = "generate")]
fn check_generated(path: &Path, expected: String) -> Result<(), BindingsError> {
    let actual = fs::read_to_string(path).map_err(|source| BindingsError::Io {
        path: path.to_path_buf(),
        source,
    })?;
    if actual == expected {
        Ok(())
    } else {
        Err(BindingsError::Drift(path.to_path_buf()))
    }
}

#[derive(Debug)]
/// Failure while writing or checking deterministic generated bindings.
#[cfg(feature = "generate")]
pub enum BindingsError {
    /// Generated file or parent directory could not be accessed.
    Io {
        /// Path involved in the failed operation.
        path: PathBuf,
        /// Underlying filesystem error.
        source: std::io::Error,
    },
    /// Existing generated output differs from the current contract.
    Drift(PathBuf),
}

#[cfg(feature = "generate")]
impl fmt::Display for BindingsError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Io { path, source } => {
                write!(formatter, "cannot access {}: {source}", path.display())
            }
            Self::Drift(path) => write!(
                formatter,
                "generated bindings differ from {}; run `wabou bindings write`",
                path.display()
            ),
        }
    }
}

#[cfg(feature = "generate")]
impl std::error::Error for BindingsError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Io { source, .. } => Some(source),
            Self::Drift(_) => None,
        }
    }
}

#[cfg(feature = "generate")]
fn sorted_capabilities(capabilities: &[Capability]) -> Vec<&Capability> {
    let mut values = capabilities.iter().collect::<Vec<_>>();
    values.sort_by(|left, right| left.name.cmp(&right.name));
    values
}

#[cfg(feature = "generate")]
fn sorted_methods(methods: &[Method]) -> Vec<&Method> {
    let mut values = methods.iter().collect::<Vec<_>>();
    values.sort_by(|left, right| left.name.cmp(&right.name));
    values
}

#[cfg(feature = "generate")]
fn assert_identifier(value: &str, kind: &str) {
    assert!(
        is_contract_identifier(value),
        "invalid {kind} identifier `{value}`"
    );
}

/// Return whether `value` is a valid identifier for Wabou's generated
/// TypeScript capability and method contracts.
pub fn is_contract_identifier(value: &str) -> bool {
    let mut chars = value.chars();
    chars
        .next()
        .is_some_and(|character| character == '_' || character.is_ascii_alphabetic())
        && chars.all(|character| character == '_' || character.is_ascii_alphanumeric())
}

#[cfg(feature = "generate")]
fn render_datatype(
    types: &Types,
    datatype: &DataType,
    phase: specta_serde::Phase,
    kind: &str,
) -> String {
    let format = specta_serde::PhasesFormat;
    let mapped_types = format
        .map_types(types)
        .unwrap_or_else(|error| panic!("cannot map capability {kind}: {error}"));
    let datatype = specta_serde::select_phase_datatype(datatype, &mapped_types, phase);
    render_mapped_datatype(&mapped_types, &datatype)
        .unwrap_or_else(|error| panic!("cannot export capability {kind}: {error}"))
}

#[cfg(feature = "generate")]
fn render_mapped_datatype(
    types: &Types,
    datatype: &DataType,
) -> Result<String, specta_typescript::Error> {
    let exporter = Typescript::default();
    match datatype {
        DataType::Reference(reference) => primitives::reference(&exporter, types, reference),
        DataType::Nullable(inner) => {
            Ok(format!("{} | null", render_mapped_datatype(types, inner)?))
        }
        datatype => primitives::inline(&exporter, types, datatype),
    }
}

#[cfg(feature = "generate")]
fn specta_declarations(types: &Types, phase: specta_serde::Phase) -> BTreeMap<String, String> {
    let mapped = specta_serde::PhasesFormat
        .map_types(types)
        .unwrap_or_else(|error| panic!("cannot map Specta declarations: {error}"));
    let names = mapped
        .into_sorted_iter()
        .map(|datatype| datatype.name.to_string())
        .collect::<BTreeSet<_>>();
    let split_bases = names
        .iter()
        .filter_map(|name| name.strip_suffix("_Serialize"))
        .filter(|base| names.contains(*base) && names.contains(&format!("{base}_Deserialize")))
        .map(str::to_owned)
        .collect::<BTreeSet<_>>();
    let mut declarations = BTreeMap::new();
    for datatype in mapped
        .into_sorted_iter()
        .filter(|datatype| datatype.ty.is_some())
    {
        let name = datatype.name.as_ref();
        if split_bases.contains(name)
            || match phase {
                specta_serde::Phase::Serialize => name
                    .strip_suffix("_Deserialize")
                    .is_some_and(|base| split_bases.contains(base)),
                specta_serde::Phase::Deserialize => name
                    .strip_suffix("_Serialize")
                    .is_some_and(|base| split_bases.contains(base)),
            }
        {
            continue;
        }
        let declaration = primitives::export(
            &Typescript::default(),
            &mapped,
            std::iter::once(datatype),
            "",
        )
        .unwrap_or_else(|error| panic!("cannot export `{}`: {error}", datatype.name));
        let declaration = declaration
            .lines()
            .map(str::trim_end)
            .collect::<Vec<_>>()
            .join("\n")
            .replacen("export type", "type", 1);
        merge_declaration(&mut declarations, datatype.name.to_string(), declaration);
    }
    declarations
}

#[cfg(feature = "generate")]
fn upper_camel_case(value: &str) -> String {
    let mut result = String::new();
    let mut uppercase = true;
    for character in value.chars() {
        if character == '_' {
            uppercase = true;
        } else if uppercase {
            result.extend(character.to_uppercase());
            uppercase = false;
        } else {
            result.push(character);
        }
    }
    result
}

#[cfg(test)]
#[cfg(feature = "generate")]
#[allow(dead_code)]
mod tests {
    use super::*;
    use serde::{Deserialize, Serialize};

    #[derive(Deserialize, Type)]
    #[serde(rename_all = "camelCase")]
    struct FunctionRequest {
        display_name: String,
    }

    #[derive(Serialize, Type)]
    struct FunctionResponse {
        accepted: bool,
    }

    #[derive(Serialize, Type)]
    struct DirectionalResponse {
        #[serde(skip_serializing_if = "Option::is_none")]
        detail: Option<String>,
        measurement: f64,
        #[specta(type = specta_typescript::Number)]
        finite_measurement: f64,
    }

    #[derive(Deserialize, Type)]
    struct DirectionalRequest {
        name: String,
        #[serde(skip_deserializing)]
        server_owned: bool,
    }

    #[derive(Deserialize, Serialize, Type)]
    struct BidirectionalPayload {
        #[serde(skip_serializing_if = "Option::is_none")]
        value: Option<String>,
    }

    mod alpha {
        use super::Type;

        #[derive(serde::Deserialize, serde::Serialize, Type)]
        pub struct Status {
            pub ready: bool,
        }
    }

    mod beta {
        use super::Type;

        #[derive(serde::Deserialize, serde::Serialize, Type)]
        pub struct Status {
            pub message: String,
        }
    }

    #[derive(Deserialize, Type)]
    struct ConflictingStatuses {
        alpha: alpha::Status,
        beta: beta::Status,
    }

    const UPDATE_FILE: JsonMethod<FunctionRequest, FunctionResponse> =
        JsonMethod::new("updateFile");
    const CURRENT_STATUS: JsonMethod<(), FunctionResponse> =
        JsonMethod::no_request("currentStatus");
    const OPTIONAL_UPDATE: JsonMethod<Option<FunctionRequest>, FunctionResponse> =
        JsonMethod::new("optionalUpdate");

    fn fixture() -> Bindings {
        Bindings::new().capability(Capability::new("workspace").method(UPDATE_FILE))
    }

    #[test]
    fn renders_dependencies_raw_abi_and_typed_client() {
        let output = fixture().render();
        assert!(output.contains("export type FunctionRequest ="));
        assert!(output.contains("displayName: string"));
        assert!(output.contains("export type NativeResult<T> = T | PromiseLike<T>"));
        assert!(output.contains("interface NativeHostCapabilities"));
        assert!(!output.contains("@wabou/solid-renderer"));
        assert!(output.contains("updateFile(request: string): NativeResult<string>"));
        assert!(output.contains("updateFile(request: FunctionRequest): Promise<FunctionResponse>"));
        assert!(output.contains("JSON.stringify(request)"));
        assert!(output.contains(
            "decodeNativeResult<FunctionResponse>(await nativeHost.workspace.updateFile"
        ));
        assert!(output.contains("\"workspace.updateFile\""));
        assert!(output.contains("useWorkspaceClient(): WorkspaceClient"));
        assert!(output.contains("createWorkspaceClient(useHost())"));
    }

    #[test]
    fn typed_contract_derives_method_and_wire_encoding() {
        let output = Bindings::new()
            .capability(Capability::new("workspace").method(UPDATE_FILE))
            .render();
        assert!(output.contains("export type FunctionRequest"));
        assert!(output.contains("updateFile(request: FunctionRequest): Promise<FunctionResponse>"));
        assert!(output.contains("nativeHost.workspace.updateFile(JSON.stringify(request))"));
    }

    #[test]
    fn typed_methods_support_empty_requests_without_contract_only_functions() {
        let output = Bindings::new()
            .capability(
                Capability::new("workspace")
                    .method(UPDATE_FILE)
                    .method(CURRENT_STATUS),
            )
            .render();

        assert!(output.contains("updateFile(request: FunctionRequest)"));
        assert!(output.contains("updateFile(request: string): NativeResult<string>"));
        assert!(output.contains("currentStatus(): Promise<FunctionResponse>"));
        assert!(output.contains("currentStatus(): NativeResult<string>"));
        assert!(output.contains("nativeHost.workspace.currentStatus()"));
        assert!(!output.contains("JSON.stringify(null)"));
    }

    #[test]
    fn nullable_values_do_not_implicitly_change_method_arity() {
        let capability = Bindings::new()
            .capability(Capability::new("workspace").method(OPTIONAL_UPDATE))
            .render();
        assert!(capability.contains(
            "optionalUpdate(request: FunctionRequest | null): Promise<FunctionResponse>"
        ));
        assert!(!capability.contains("optionalUpdate(request?:"));

        let module = FunctionModule::new("NativeFiles")
            .method(NativeMethod::<(Option<String>,), bool>::sync(
                "confirm",
                &["value"],
            ))
            .render();
        assert!(module.contains("confirm(value: string | null): boolean"));
        assert!(!module.contains("confirm(value?:"));
    }

    #[test]
    fn contract_identifier_grammar_is_explicit_and_shared() {
        assert!(is_contract_identifier("workspace"));
        assert!(is_contract_identifier("_workspace2"));
        for invalid in ["", "1workspace", "work-space", "工作区"] {
            assert!(!is_contract_identifier(invalid), "accepted {invalid:?}");
        }
    }

    #[test]
    fn flat_function_modules_preserve_synchronous_signatures() {
        let output = FunctionModule::new("NativeFiles")
            .method(
                NativeMethod::<(FunctionRequest,), FunctionResponse>::asynchronous(
                    "updateFile",
                    &["request"],
                ),
            )
            .method(NativeMethod::<(), FunctionResponse>::sync(
                "currentStatus",
                &[],
            ))
            .render();
        assert!(output.contains("export interface NativeFiles"));
        assert!(output.contains("updateFile(request: FunctionRequest): Promise<FunctionResponse>"));
        assert!(output.contains("currentStatus(): FunctionResponse"));
    }

    #[test]
    fn response_bindings_follow_serde_shape_and_explicit_number_contracts() {
        const READ: JsonMethod<(), DirectionalResponse> = JsonMethod::no_request("read");
        let output = Bindings::new()
            .capability(Capability::new("metrics").method(READ))
            .render();

        assert!(output.contains("detail?: string | null"));
        assert!(output.contains("measurement: number | null"));
        assert!(output.contains("finite_measurement: number"));
        assert!(output.contains("read(): Promise<DirectionalResponse_Serialize>"));
        assert!(
            output.contains("export type DirectionalResponse = DirectionalResponse_Serialize;")
        );
        assert!(!output.contains("DirectionalResponse_Deserialize"));
    }

    #[test]
    fn request_bindings_export_only_the_deserialization_shape() {
        const WRITE: JsonMethod<DirectionalRequest, bool> = JsonMethod::new("write");
        let output = Bindings::new()
            .capability(Capability::new("metrics").method(WRITE))
            .render();

        assert!(output.contains("write(request: DirectionalRequest_Deserialize)"));
        assert!(output.contains("name: string"));
        assert!(!output.contains("server_owned"));
        assert!(
            output.contains("export type DirectionalRequest = DirectionalRequest_Deserialize;")
        );
        assert!(!output.contains("DirectionalRequest_Serialize"));
    }

    #[test]
    fn bidirectional_contracts_keep_explicit_phase_names() {
        const ROUND_TRIP: JsonMethod<BidirectionalPayload, BidirectionalPayload> =
            JsonMethod::new("roundTrip");
        let output = Bindings::new()
            .capability(Capability::new("workspace").method(ROUND_TRIP))
            .render();

        assert!(output.contains("BidirectionalPayload_Deserialize"));
        assert!(output.contains("BidirectionalPayload_Serialize"));
        assert!(!output.contains("type BidirectionalPayload ="));
    }

    #[test]
    #[should_panic(expected = "conflicting TypeScript declaration for `Status`")]
    fn rejects_conflicting_dto_names_in_one_generated_module() {
        const ALPHA: JsonMethod<(), alpha::Status> = JsonMethod::no_request("alpha");
        const BETA: JsonMethod<(), beta::Status> = JsonMethod::no_request("beta");

        let _ = Bindings::new()
            .capability(Capability::new("first").method(ALPHA))
            .capability(Capability::new("second").method(BETA))
            .render();
    }

    #[test]
    #[should_panic(expected = "conflicting TypeScript declaration for `Status`")]
    fn rejects_conflicting_dto_names_inside_one_method_graph() {
        const STATUS_PAIR: JsonMethod<ConflictingStatuses, ()> = JsonMethod::new("statusPair");

        let _ = Bindings::new()
            .capability(Capability::new("workspace").method(STATUS_PAIR))
            .render();
    }

    #[test]
    fn check_reports_drift_without_rewriting_the_file() {
        let path = std::env::temp_dir().join(format!(
            "wabou-bindgen-{}-{}.ts",
            std::process::id(),
            line!()
        ));
        fixture().write(&path).unwrap();
        fixture().check(&path).unwrap();
        fs::write(&path, "stale").unwrap();
        assert!(matches!(
            fixture().check(&path),
            Err(BindingsError::Drift(_))
        ));
        assert_eq!(fs::read_to_string(&path).unwrap(), "stale");
        fs::remove_file(path).unwrap();
    }
}
