import { defineWabouConfig, defineWabouTheme } from "@wabou/vite";

export default defineWabouConfig({
  outDir: "../../dist/7guis/resources",
  intl: {
    locales: ["en"],
    timeZones: "golden",
  },
  theme: defineWabouTheme({
    default: "dark",
    themes: {
      dark: {
        appearance: "dark",
        colors: {
          canvas: "#090d14",
          surface: "#121925",
          "surface-muted": "#0d131d",
          input: "#0a1019",
          control: "#202b3b",
          "control-hover": "#2b3a4f",
          "control-pressed": "#3b4d66",
          selected: "#15395d",
          primary: "#f4f7fb",
          secondary: "#c4cfdd",
          muted: "#8492a6",
          subtle: "#253144",
          strong: "#37465d",
          accent: "#0ea5e9",
          "accent-hover": "#0284c7",
          "accent-pressed": "#0369a1",
          "on-accent": "#082f49",
          danger: "#ef4444",
          "danger-hover": "#dc2626",
          "danger-pressed": "#b91c1c",
          "danger-surface": "#3a1117",
          "danger-primary": "#fca5a5",
          "success-surface": "#0d342b",
          "success-primary": "#6ee7b7",
          focus: "#7dd3fc",
        },
      },
      light: {
        appearance: "light",
        colors: {
          canvas: "#f4f7fb",
          surface: "#ffffff",
          "surface-muted": "#f7f9fc",
          input: "#ffffff",
          control: "#edf2f7",
          "control-hover": "#e2e8f0",
          "control-pressed": "#cbd5e1",
          selected: "#e0f2fe",
          primary: "#111827",
          secondary: "#334155",
          muted: "#637289",
          subtle: "#dce3ec",
          strong: "#c2ccd9",
          accent: "#0369a1",
          "accent-hover": "#075985",
          "accent-pressed": "#0c4a6e",
          "on-accent": "#ffffff",
          danger: "#dc2626",
          "danger-hover": "#b91c1c",
          "danger-pressed": "#991b1b",
          "danger-surface": "#fef2f2",
          "danger-primary": "#991b1b",
          "success-surface": "#ecfdf5",
          "success-primary": "#047857",
          focus: "#0284c7",
        },
      },
    },
  }),
});
