[package]
name = "wabou-accessibility-vello"
version.workspace = true
edition = "2024"
description = "Winit AccessKit adapter for Wabou's Vello backend."
publish = false
license.workspace = true

[dependencies]
accesskit = "0.24.1"
accesskit_xplat = "=0.1.1"
raw-window-handle = "0.6"
winit.workspace = true
wabou-accessibility.workspace = true
