import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

type Entry = {
  name: string;
  direction: "host" | "guest";
  owner: string;
  feature?: string;
  kind: "const" | "function";
  type?: string;
  params?: [string, string][];
  returns?: string;
};

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const sourcePath = resolve(root, "packages/core/host-abi.json");
const schema = JSON.parse(await readFile(sourcePath, "utf8")) as {
  version: number;
  entries: Entry[];
};

if (schema.version !== 1)
  throw new Error(`unsupported Host ABI schema v${schema.version}`);
const names = new Set<string>();
for (const entry of schema.entries) {
  if (!/^__wabou_[a-z0-9_]+$/.test(entry.name)) {
    throw new Error(`invalid Host ABI name: ${entry.name}`);
  }
  if (names.has(entry.name))
    throw new Error(`duplicate Host ABI name: ${entry.name}`);
  names.add(entry.name);
  if (entry.kind === "const" && !entry.type)
    throw new Error(`${entry.name} has no type`);
  if (entry.kind === "function" && (!entry.params || !entry.returns)) {
    throw new Error(`${entry.name} has no function signature`);
  }
}

const header =
  "// AUTO-GENERATED by scripts/gen-host-abi.ts. Do not edit by hand.\n";
const declarations = schema.entries
  .map((entry) => {
    if (entry.kind === "const") return `  const ${entry.name}: ${entry.type};`;
    const params = (entry.params ?? [])
      .map(([name, type]) => `${name}: ${type}`)
      .join(", ");
    return `  function ${entry.name}(${params}): ${entry.returns};`;
  })
  .join("\n");
const typescript = `${header}export {};\n\ndeclare global {\n${declarations}\n}\n`;

const rustEntries = schema.entries
  .map(
    (entry) =>
      `    HostAbiEntry { name: "${entry.name}", direction: Direction::${entry.direction === "host" ? "Host" : "Guest"}, owner: "${entry.owner}", feature: ${entry.feature ? `Some("${entry.feature}")` : "None"} },`,
  )
  .join("\n");
const rust = `${header}#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum Direction { Host, Guest }

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) struct HostAbiEntry {
    pub(crate) name: &'static str,
    pub(crate) direction: Direction,
    pub(crate) owner: &'static str,
    pub(crate) feature: Option<&'static str>,
}

pub(crate) const HOST_ABI: &[HostAbiEntry] = &[
${rustEntries}
];
`;

const rows = schema.entries
  .map(
    (entry) =>
      `| \`${entry.name}\` | ${entry.direction} | ${entry.owner} | ${entry.feature ?? "always"} |`,
  )
  .join("\n");
const docs = `<!-- AUTO-GENERATED by scripts/gen-host-abi.ts. Do not edit by hand. -->
# Host ABI inventory

Source of truth: \`packages/core/host-abi.json\`.

| Global | Direction | Owner | Availability |
| --- | --- | --- | --- |
${rows}
`;

const outputs = [
  [resolve(root, "packages/core/src/generated/host-abi.ts"), typescript],
  [resolve(root, "crates/wabou-quick/src/gen/host_abi.rs"), rust],
  [resolve(root, "docs/host-abi.md"), docs],
] as const;
for (const [path, contents] of outputs) {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, contents);
  console.log(`wrote ${path}`);
}

const formatTypescript = Bun.spawn(
  [Bun.which("bun") ?? "bun", "x", "biome", "format", "--write", outputs[0][0]],
  { cwd: root, stdout: "inherit", stderr: "inherit" },
);
if ((await formatTypescript.exited) !== 0) {
  throw new Error("failed to format generated Host ABI declarations");
}

const formatRust = Bun.spawn(["rustfmt", "--edition", "2024", outputs[1][0]], {
  cwd: root,
  stdout: "inherit",
  stderr: "inherit",
});
if ((await formatRust.exited) !== 0) {
  throw new Error("failed to format generated Host ABI inventory");
}
