import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const manifestProcess = Bun.spawn(
  ["cargo", "run", "-q", "-p", "wabou-style", "--bin", "wabou-style-manifest"],
  { cwd: resolve(import.meta.dir, ".."), stdout: "pipe", stderr: "inherit" },
);
const json = await new Response(manifestProcess.stdout).text();
if ((await manifestProcess.exited) !== 0)
  throw new Error("failed to export utility manifest");
const manifest = JSON.parse(json) as {
  spacing: Record<string, number>;
  colors: Record<string, number>;
  staticUtilities: Record<string, unknown>;
};
await writeFile(
  resolve(import.meta.dir, "../packages/unocss-preset/generated/manifest.json"),
  json,
);

const union = (values: string[]) =>
  values.length
    ? values.map((value) => JSON.stringify(value)).join(" | ")
    : "never";
const types = `// AUTO-GENERATED by scripts/gen-utility-manifest.ts. Do not edit.
export type WabouStaticUtility = ${union(Object.keys(manifest.staticUtilities))};
export type WabouSpacingToken = ${union(Object.keys(manifest.spacing))};
export type WabouColorToken = ${union(Object.keys(manifest.colors))};

type ArbitraryLength = \`[\${number}px]\` | \`[\${number}rem]\` | \`[\${number}%]\`;
type BarePercent = \`\${number}%\`;
type SpacingPrefix = "p" | "px" | "py" | "pt" | "pr" | "pb" | "pl" | "m" | "mx" | "my" | "mt" | "mr" | "mb" | "ml" | "gap";
type DimensionPrefix = "w" | "h" | "min-w" | "min-h" | "max-w" | "max-h" | "inset" | "top" | "right" | "bottom" | "left";
type ColorPrefix = "bg" | "text" | "border";
export type WabouDynamicUtility =
  | \`\${SpacingPrefix}-\${WabouSpacingToken | ArbitraryLength}\`
  | \`\${DimensionPrefix}-\${WabouSpacingToken | ArbitraryLength | "full" | BarePercent}\`
  | \`\${ColorPrefix}-\${WabouColorToken}\`
  | \`\${ColorPrefix}-\${WabouColorToken}/\${number}\`
  | \`opacity-\${number}\`;
export type WabouBaseUtility = WabouStaticUtility | WabouDynamicUtility;
export type WabouUtility = WabouBaseUtility;
`;
await mkdir(resolve(import.meta.dir, "../packages/style/generated"), {
  recursive: true,
});
await writeFile(
  resolve(import.meta.dir, "../packages/style/generated/utility-types.ts"),
  types,
);
const formatProcess = Bun.spawn(
  [
    Bun.which("bun") ?? "bun",
    "x",
    "biome",
    "format",
    "--write",
    resolve(import.meta.dir, "../packages/style/generated/utility-types.ts"),
  ],
  { cwd: resolve(import.meta.dir, ".."), stdout: "inherit", stderr: "inherit" },
);
if ((await formatProcess.exited) !== 0)
  throw new Error("failed to format generated utility types");
