import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const entrypoints = [
  resolve(root, "packages/core/src/prelude/bootstrap.ts"),
  resolve(root, "packages/core/src/prelude/platform.ts"),
];
const outputPath = resolve(root, "crates/wabou-quick/src/gen/core-prelude.js");

const stages: string[] = [];
for (const entrypoint of entrypoints) {
  const result = await Bun.build({
    entrypoints: [entrypoint],
    format: "iife",
    target: "browser",
    minify: true,
  });
  if (!result.success) {
    for (const log of result.logs) console.error(log);
    throw new Error(`failed to generate ${entrypoint}`);
  }
  const output = result.outputs.find((file) => file.kind === "entry-point");
  if (!output) throw new Error(`${entrypoint} produced no entry point`);
  stages.push(await output.text());
}

const header =
  "// AUTO-GENERATED by scripts/gen-core-prelude.ts. Do not edit by hand.\n";
await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, header + stages.join("\n"));
console.log(`wrote ${outputPath}`);
