import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const entrypoint = resolve(root, "packages/vite-runtime/src/client.ts");
const outputPath = resolve(root, "crates/wabou-quick/src/gen/vite-client.js");

const result = await Bun.build({
  entrypoints: [entrypoint],
  format: "esm",
  target: "browser",
});

if (!result.success) {
  for (const log of result.logs) console.error(log);
  throw new Error("failed to generate the Vite runtime");
}

const output = result.outputs.find((file) => file.kind === "entry-point");
if (!output) throw new Error("Vite runtime build produced no entry point");

const source = await output.text();
const header =
  "// AUTO-GENERATED by scripts/gen-vite-runtime.ts. Do not edit by hand.\n";
await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, header + source);
console.log(`wrote ${outputPath}`);
