import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const entrypoint = resolve(root, "packages/animation/test/runtime-fixture.ts");
const outputPath = resolve(
  root,
  "crates/wabou-quick/src/gen/motion-test-runtime.js",
);
const result = await Bun.build({
  entrypoints: [entrypoint],
  format: "iife",
  target: "browser",
  minify: true,
});
if (!result.success) throw new Error("failed to generate Motion test runtime");
const output = result.outputs.find((file) => file.kind === "entry-point");
if (!output) throw new Error("Motion test runtime produced no entry point");
await mkdir(dirname(outputPath), { recursive: true });
await writeFile(
  outputPath,
  `// AUTO-GENERATED by scripts/gen-motion-test-runtime.ts.\n${await output.text()}`,
);
console.log(`wrote ${outputPath}`);
