// Codegen: emit Rust opcode + event-code constants from the TS source of truth
// (packages/protocol/src/index.ts). Run with `bun run gen`. Output:
// crates/wabou-quick/src/gen/op.rs, which src/protocol.rs `include!`s.
//
// Parsing is deliberately naive — the OP and EVENT_CODE objects are plain
// `Name: 0xNN` / `Name: N` literals. If that shape ever changes, update the
// parser here; the roundtrip tests in protocol.rs will catch a mismatch.

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = readFileSync(
  resolve(ROOT, "packages/protocol/src/index.ts"),
  "utf8",
);
const OUT = resolve(ROOT, "crates/wabou-quick/src/gen/op.rs");

interface Entry {
  /** TS name, e.g. CreateElement */
  name: string;
  /** Rust SCREAMING_SNAKE name, e.g. CREATE_ELEMENT */
  rustName: string;
  /** numeric value */
  value: number;
  /** raw hex/dec token as written in TS, e.g. 0x01 */
  raw: string;
}

function parseObject(source: string, objName: string): Entry[] {
  // Grab the `const NAME = { ... } as const;` block. Match the `const NAME`
  // boundary (not a substring in a comment) so a top-of-file doc comment
  // mentioning the name doesn't mislead the brace search.
  const start = source.search(new RegExp(`\\bconst\\s+${objName}\\b`));
  if (start === -1) throw new Error(`could not find ${objName}`);
  const braceOpen = source.indexOf("{", start);
  const braceClose = source.indexOf("}", braceOpen);
  const body = source.slice(braceOpen + 1, braceClose);

  const entries: Entry[] = [];
  // Match `Name: <value>,` (value is 0xNN or decimal, possibly negative).
  const re = /([A-Za-z_][A-Za-z0-9_]*)\s*:\s*(0x[0-9a-fA-F]+|-?\d+)\s*,/g;
  for (const m of body.matchAll(re)) {
    const name = m[1];
    const raw = m[2];
    const value = raw.startsWith("0x") ? parseInt(raw, 16) : parseInt(raw, 10);
    entries.push({ name, rustName: toScreamingSnake(name), value, raw });
  }
  return entries;
}

function toScreamingSnake(name: string): string {
  // CamelCase -> CAMEL_CASE
  return name.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toUpperCase();
}

function emit(
  entries: { label: string; items: Entry[]; rustType?: "u8" | "u32" }[],
): string {
  const parts: string[] = [
    "// AUTO-GENERATED by scripts/gen-rust-op.ts from packages/protocol/src/index.ts.",
    "// Do not edit by hand — run `bun run gen`.",
    "",
  ];
  for (const { label, items, rustType = "u8" } of entries) {
    parts.push(`pub mod ${label} {`);
    if (label === "event_data") {
      parts.push(`    pub const LEN: usize = ${items.length};`);
    }
    for (const e of items) {
      parts.push(`    pub const ${e.rustName}: ${rustType} = ${e.raw};`);
    }
    parts.push("}");
    parts.push("");
  }
  return parts.join("\n");
}

const op = parseObject(SRC, "OP");
const event = parseObject(SRC, "EVENT_CODE");
const eventData = parseObject(SRC, "EVENT_DATA_SLOT");
const hostFrame = parseObject(SRC, "HOST_FRAME");
const hostRecord = parseObject(SRC, "HOST_RECORD_KIND");
const hostNodePayload = parseObject(SRC, "HOST_NODE_PAYLOAD");

if (op.length === 0 || event.length === 0 || eventData.length === 0) {
  throw new Error(
    `parse failed: got ${op.length} opcodes, ${event.length} events, ${eventData.length} event-data slots`,
  );
}

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(
  OUT,
  emit([
    { label: "op", items: op },
    { label: "event", items: event },
    { label: "event_data", items: eventData },
    { label: "host_frame", items: hostFrame, rustType: "u32" },
    { label: "host_record", items: hostRecord },
    { label: "host_node_payload", items: hostNodePayload },
  ]),
);

console.log(`wrote ${OUT}`);
console.log(
  `  ${op.length} opcodes, ${event.length} event codes, ${eventData.length} event-data slots, ${hostRecord.length} host records`,
);
