import { defineWabouConfig } from "@wabou/vite";

export default defineWabouConfig({
  ignoreClasses: ["lucide", "lucide-*"],
  outDir: "../../dist/meow-starter/debug/resources",
  globalName: "MeowStarterWabouApp",
  themeContrast: "error",
  theme: {
    default: "light",
    themes: {
      light: {
        appearance: "light",
        colors: {
          canvas: "#fdfdfc",
          surface: "#ffffff",
          "surface-muted": "#f7f8f9",
          input: "#ffffff",
          control: "#f5f7f8",
          "control-hover": "#edf1f3",
          "control-pressed": "#e2e8eb",
          selected: "#dff6f2",
          primary: "#0c1b2f",
          secondary: "#43546a",
          muted: "#5e6b7c",
          subtle: "#e2e7eb",
          strong: "#bec9d1",
          accent: "#08796f",
          "accent-hover": "#07675f",
          "accent-pressed": "#05564f",
          "on-accent": "#ffffff",
          danger: "#dc4c4c",
          "danger-hover": "#bd3838",
          "danger-pressed": "#9c2c2c",
          "danger-surface": "#fff0f0",
          "danger-primary": "#9f2525",
          "success-surface": "#e7f8f4",
          "success-primary": "#087d70",
          "indigo-surface": "#eef0ff",
          "indigo-primary": "#4f46b8",
          "blue-surface": "#eaf4ff",
          "blue-primary": "#1769aa",
          "coral-surface": "#fff0ec",
          "coral-primary": "#b9472f",
          focus: "#159f92",
          sidebar: "#102338",
          "sidebar-raised": "#1a334b",
          "sidebar-primary": "#f4fbff",
          "sidebar-muted": "#b6c6d5",
        },
      },
      dark: {
        appearance: "dark",
        colors: {
          canvas: "#0d1520",
          surface: "#131f2d",
          "surface-muted": "#182838",
          input: "#182838",
          control: "#1d3042",
          "control-hover": "#263d52",
          "control-pressed": "#304a61",
          selected: "#17473f",
          primary: "#f0f7fa",
          secondary: "#bdcbd6",
          muted: "#8fa2b2",
          subtle: "#2b4052",
          strong: "#456176",
          accent: "#52d7c6",
          "accent-hover": "#6be0d0",
          "accent-pressed": "#39bbaa",
          "on-accent": "#09201e",
          danger: "#ff7777",
          "danger-hover": "#ff8e8e",
          "danger-pressed": "#df5c5c",
          "danger-surface": "#421f27",
          "danger-primary": "#ffb5b5",
          "success-surface": "#123c37",
          "success-primary": "#7de3d5",
          "indigo-surface": "#252849",
          "indigo-primary": "#b9b8ff",
          "blue-surface": "#17324a",
          "blue-primary": "#9bd0ff",
          "coral-surface": "#452722",
          "coral-primary": "#ffb6a3",
          focus: "#63e0d0",
          sidebar: "#08131f",
          "sidebar-raised": "#15283a",
          "sidebar-primary": "#f4fbff",
          "sidebar-muted": "#a9bdcc",
        },
      },
    },
  },
});
