import { defineWabouConfig } from "@wabou/vite";

export default defineWabouConfig({
  ignoreClasses: ["lucide", "lucide-*"],
  outDir: "../../dist/meow-starter/debug/resources",
  globalName: "MeowStarterWabouApp",
  themeContrast: "error",
  theme: {
    default: "light",
    themes: {
      light: {
        appearance: "light",
        colors: {
          canvas: "#f7f9fc",
          surface: "#ffffff",
          "surface-muted": "#f1f5f9",
          input: "#ffffff",
          control: "#f3f6f9",
          "control-hover": "#e9f0f5",
          "control-pressed": "#dce7ed",
          selected: "#dff6f2",
          primary: "#102038",
          secondary: "#53647a",
          muted: "#637187",
          subtle: "#dce4eb",
          strong: "#b7c4cf",
          accent: "#08796f",
          "accent-hover": "#07675f",
          "accent-pressed": "#05564f",
          "on-accent": "#ffffff",
          danger: "#dc4c4c",
          "danger-hover": "#bd3838",
          "danger-pressed": "#9c2c2c",
          "danger-surface": "#fff0f0",
          "danger-primary": "#9f2525",
          "success-surface": "#e7f8f4",
          "success-primary": "#087d70",
          focus: "#159f92",
          sidebar: "#102338",
          "sidebar-raised": "#1a334b",
          "sidebar-primary": "#f4fbff",
          "sidebar-muted": "#b6c6d5",
          coral: "#ff6565",
        },
      },
      dark: {
        appearance: "dark",
        colors: {
          canvas: "#0d1520",
          surface: "#131f2d",
          "surface-muted": "#182838",
          input: "#182838",
          control: "#1d3042",
          "control-hover": "#263d52",
          "control-pressed": "#304a61",
          selected: "#17473f",
          primary: "#f0f7fa",
          secondary: "#bdcbd6",
          muted: "#8fa2b2",
          subtle: "#2b4052",
          strong: "#456176",
          accent: "#52d7c6",
          "accent-hover": "#6be0d0",
          "accent-pressed": "#39bbaa",
          "on-accent": "#09201e",
          danger: "#ff7777",
          "danger-hover": "#ff8e8e",
          "danger-pressed": "#df5c5c",
          "danger-surface": "#421f27",
          "danger-primary": "#ffb5b5",
          "success-surface": "#123c37",
          "success-primary": "#7de3d5",
          focus: "#63e0d0",
          sidebar: "#08131f",
          "sidebar-raised": "#15283a",
          "sidebar-primary": "#f4fbff",
          "sidebar-muted": "#a9bdcc",
          coral: "#ff7777",
        },
      },
    },
  },
});
