[package]
name = "motrix-wabou"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "motrix-wabou"
path = "src/main.rs"

[dependencies]
directories = { workspace = true }
gosh-dl = { workspace = true }
jiff = { workspace = true }
open = { workspace = true }
portmapper = "0.19.1"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
snafu = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync", "time"] }
trash = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
uuid = { workspace = true, features = ["v4"] }
wabou = { workspace = true, features = ["tray"] }
