import { defineWabouConfig } from "@wabou/vite";

export default defineWabouConfig({
  ignoreClasses: ["lucide", "lucide-*"],
  outDir: "../../dist/motrix-wabou/resources",
  globalName: "MotrixWabouApp",
  theme: {
    default: "light",
    themes: {
      light: {
        appearance: "light",
        colors: {
          canvas: "#f7f7f8",
          surface: "#ffffff",
          "surface-muted": "#f2f3f5",
          input: "#ffffff",
          control: "#f3f4f6",
          "control-hover": "#e9eaed",
          "control-pressed": "#dedfe3",
          selected: "#eeeeef",
          primary: "#111216",
          secondary: "#656b75",
          muted: "#9299a6",
          subtle: "#e2e4e8",
          strong: "#c7cbd2",
          accent: "#2f81f7",
          "accent-hover": "#1f6feb",
          "accent-pressed": "#175cc5",
          "on-accent": "#ffffff",
          danger: "#dc2626",
          "danger-hover": "#b91c1c",
          "danger-pressed": "#991b1b",
          "danger-surface": "#fef2f2",
          "danger-primary": "#991b1b",
          "success-surface": "#ecfdf5",
          "success-primary": "#047857",
          "chart-download": "#2f81f7",
          "chart-upload": "#a855f7",
          "activity-1": "#bfdbfe",
          "activity-2": "#60a5fa",
          "activity-3": "#2563eb",
          "activity-4": "#1e40af",
          focus: "#0d74ce",
        },
      },
      dark: {
        appearance: "dark",
        colors: {
          canvas: "#101115",
          surface: "#18191e",
          "surface-muted": "#202127",
          input: "#202127",
          control: "#25272e",
          "control-hover": "#30323a",
          "control-pressed": "#3a3d46",
          selected: "#2b2d34",
          primary: "#f0f3f6",
          secondary: "#b1bac4",
          muted: "#7d8590",
          subtle: "#30323a",
          strong: "#4a4d58",
          accent: "#2f81f7",
          "accent-hover": "#388bfd",
          "accent-pressed": "#1f6feb",
          "on-accent": "#ffffff",
          danger: "#f85149",
          "danger-hover": "#da3633",
          "danger-pressed": "#b62324",
          "danger-surface": "#3d1518",
          "danger-primary": "#ffb1aa",
          "success-surface": "#12351f",
          "success-primary": "#7ee787",
          "chart-download": "#58a6ff",
          "chart-upload": "#c084fc",
          "activity-1": "#1e3a5f",
          "activity-2": "#1d4f91",
          "activity-3": "#2f81f7",
          "activity-4": "#79c0ff",
          focus: "#58a6ff",
        },
      },
    },
  },
});
