import { defineWabouConfig } from "@wabou/vite";

export default defineWabouConfig({
  ignoreClasses: ["lucide", "lucide-*"],
  outDir: "../../dist/manga-ocr-wabou/resources",
  globalName: "MangaOcrWabouApp",
  theme: {
    default: "light",
    themes: {
      light: {
        appearance: "light",
        colors: {
          canvas: "#f7f8fb",
          surface: "#ffffff",
          "surface-muted": "#f3f4f7",
          input: "#ffffff",
          control: "#eef1f6",
          "control-hover": "#e5e9f1",
          "control-pressed": "#dce2ec",
          selected: "#ede9fe",
          primary: "#171923",
          secondary: "#4b5565",
          muted: "#788294",
          subtle: "#dce1e9",
          strong: "#aeb7c5",
          accent: "#7c3aed",
          "accent-hover": "#6d28d9",
          "accent-pressed": "#5b21b6",
          "on-accent": "#ffffff",
          danger: "#dc2626",
          "danger-hover": "#b91c1c",
          "danger-pressed": "#991b1b",
          "danger-surface": "#fef2f2",
          "danger-primary": "#b91c1c",
          "success-surface": "#ecfdf5",
          "success-primary": "#047857",
          focus: "#7c3aed",
        },
      },
      dark: {
        appearance: "dark",
        colors: {
          canvas: "#0c0d10",
          surface: "#15171c",
          "surface-muted": "#1c1f26",
          input: "#1c1f26",
          control: "#232731",
          "control-hover": "#2c3240",
          "control-pressed": "#353d4d",
          selected: "#293140",
          primary: "#f3f4f6",
          secondary: "#c1c7d0",
          muted: "#8992a3",
          subtle: "#2a2f39",
          strong: "#414957",
          accent: "#8b5cf6",
          "accent-hover": "#7c3aed",
          "accent-pressed": "#6d28d9",
          "on-accent": "#ffffff",
          danger: "#ef4444",
          "danger-hover": "#dc2626",
          "danger-pressed": "#b91c1c",
          "danger-surface": "#35171b",
          "danger-primary": "#fca5a5",
          "success-surface": "#102d25",
          "success-primary": "#6ee7b7",
          focus: "#a78bfa",
        },
      },
    },
  },
});
