[package]
name = "gallery"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "gallery"
path = "src/main.rs"

[[example]]
name = "gallery-bindgen"
path = "examples/wabou-bindgen.rs"

[dependencies]
image = { workspace = true, features = ["png"] }
serde = { workspace = true, features = ["derive"] }
snafu = { workspace = true }
wabou = { workspace = true, features = ["bindings"] }
