[package]
name = "gallery"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "gallery"
path = "src/main.rs"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
snafu = { workspace = true }
specta = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
wabou-bindings = { workspace = true }
wabou-quick = { workspace = true }
