import { paraglideVitePlugin } from "@inlang/paraglide-js";
import { defineWabouConfig } from "@wabou/vite";

export default defineWabouConfig(({ mode }) => ({
  entry: mode === "layout-test" ? "ui/layout-fixtures.tsx" : "ui/index.tsx",
  outDir: "../../dist/gallery/resources",
  vite: {
    plugins: [
      paraglideVitePlugin({
        project: "./project.inlang",
        outdir: "./ui/paraglide",
        strategy: ["baseLocale"],
        isServer: "false",
        emitTsDeclarations: true,
      }),
    ],
  },
  intl: {
    locales: ["en", "zh", "de"],
    timeZones: "golden",
  },
  theme: {
    default: "dark",
    themes: {
      dark: {
        appearance: "dark",
        colors: {
          canvas: "#111113",
          surface: "#1b1b1f",
          "surface-muted": "#18181b",
          input: "#18181b",
          control: "#212225",
          "control-hover": "#2b2d31",
          "control-pressed": "#34363b",
          selected: "#27384d",
          primary: "#eeeeef",
          secondary: "#b4b4bb",
          muted: "#8b8d98",
          subtle: "#303136",
          strong: "#484950",
          accent: "#0090ff",
          "accent-hover": "#3b9eff",
          "accent-pressed": "#0588f0",
          "on-accent": "#ffffff",
          danger: "#ef4444",
          "danger-hover": "#dc2626",
          "danger-pressed": "#b91c1c",
          "danger-surface": "#450a0a",
          "danger-primary": "#fecaca",
          "success-surface": "#064e3b",
          "success-primary": "#a7f3d0",
          focus: "#5eb1ef",
        },
      },
      light: {
        appearance: "light",
        colors: {
          canvas: "#fcfcfd",
          surface: "#ffffff",
          "surface-muted": "#f9f9fb",
          input: "#ffffff",
          control: "#f0f0f3",
          "control-hover": "#e8e8ec",
          "control-pressed": "#e0e1e6",
          selected: "#e1f0ff",
          primary: "#1c2024",
          secondary: "#60646c",
          muted: "#8b8d98",
          subtle: "#d9d9e0",
          strong: "#b9bbc3",
          accent: "#0090ff",
          "accent-hover": "#0588f0",
          "accent-pressed": "#0d74ce",
          "on-accent": "#ffffff",
          danger: "#dc2626",
          "danger-hover": "#b91c1c",
          "danger-pressed": "#991b1b",
          "danger-surface": "#fef2f2",
          "danger-primary": "#991b1b",
          "success-surface": "#ecfdf5",
          "success-primary": "#047857",
          focus: "#0d74ce",
        },
      },
      violet: {
        appearance: "dark",
        colors: {
          canvas: "#0f0b1a",
          surface: "#1a1328",
          "surface-muted": "#151020",
          input: "#110d1c",
          control: "#2d2340",
          "control-hover": "#403158",
          "control-pressed": "#594276",
          selected: "#4c356b",
          primary: "#faf7ff",
          secondary: "#ddd6fe",
          muted: "#a78bba",
          subtle: "#352744",
          strong: "#5b4670",
          accent: "#8b5cf6",
          "accent-hover": "#7c3aed",
          "accent-pressed": "#6d28d9",
          "on-accent": "#ffffff",
          danger: "#fb7185",
          "danger-hover": "#f43f5e",
          "danger-pressed": "#e11d48",
          "danger-surface": "#4c1427",
          "danger-primary": "#fecdd3",
          "success-surface": "#123c35",
          "success-primary": "#99f6e4",
          focus: "#c4b5fd",
        },
      },
    },
  },
}));
