import { defineWabouConfig } from "@wabou/vite";

export default defineWabouConfig({
  outDir: "../../dist/gallery/resources",
  theme: {
    default: "dark",
    themes: {
      dark: {
        appearance: "dark",
        colors: {
          canvas: "#0a0e13",
          surface: "#151b24",
          "surface-muted": "#111720",
          input: "#0d1219",
          control: "#273244",
          "control-hover": "#334155",
          "control-pressed": "#475569",
          selected: "#3b4c63",
          primary: "#f1f5f9",
          secondary: "#cbd5e1",
          muted: "#94a3b8",
          subtle: "#273244",
          strong: "#334155",
          accent: "#0ea5e9",
          "accent-hover": "#0284c7",
          "accent-pressed": "#0369a1",
          "on-accent": "#ffffff",
          danger: "#ef4444",
          "danger-hover": "#dc2626",
          "danger-pressed": "#b91c1c",
          "danger-surface": "#450a0a",
          "danger-primary": "#fecaca",
          "success-surface": "#064e3b",
          "success-primary": "#a7f3d0",
          focus: "#7dd3fc",
        },
      },
      light: {
        appearance: "light",
        colors: {
          canvas: "#f8fafc",
          surface: "#ffffff",
          "surface-muted": "#f8fafc",
          input: "#ffffff",
          control: "#f1f5f9",
          "control-hover": "#e2e8f0",
          "control-pressed": "#cbd5e1",
          selected: "#e0f2fe",
          primary: "#0f172a",
          secondary: "#334155",
          muted: "#64748b",
          subtle: "#e2e8f0",
          strong: "#cbd5e1",
          accent: "#0284c7",
          "accent-hover": "#0369a1",
          "accent-pressed": "#075985",
          "on-accent": "#ffffff",
          danger: "#dc2626",
          "danger-hover": "#b91c1c",
          "danger-pressed": "#991b1b",
          "danger-surface": "#fef2f2",
          "danger-primary": "#991b1b",
          "success-surface": "#ecfdf5",
          "success-primary": "#047857",
          focus: "#0284c7",
        },
      },
      violet: {
        appearance: "dark",
        colors: {
          canvas: "#0f0b1a",
          surface: "#1a1328",
          "surface-muted": "#151020",
          input: "#110d1c",
          control: "#2d2340",
          "control-hover": "#403158",
          "control-pressed": "#594276",
          selected: "#4c356b",
          primary: "#faf7ff",
          secondary: "#ddd6fe",
          muted: "#a78bba",
          subtle: "#352744",
          strong: "#5b4670",
          accent: "#8b5cf6",
          "accent-hover": "#7c3aed",
          "accent-pressed": "#6d28d9",
          "on-accent": "#ffffff",
          danger: "#fb7185",
          "danger-hover": "#f43f5e",
          "danger-pressed": "#e11d48",
          "danger-surface": "#4c1427",
          "danger-primary": "#fecdd3",
          "success-surface": "#123c35",
          "success-primary": "#99f6e4",
          focus: "#c4b5fd",
        },
      },
    },
  },
});
