import { paraglideVitePlugin } from "@inlang/paraglide-js";
import { defineWabouConfig } from "@wabou/vite";

export default defineWabouConfig(({ mode }) => ({
  entry: mode === "layout-test" ? "ui/layout-fixtures.tsx" : "ui/index.tsx",
  vite: {
    plugins: [
      paraglideVitePlugin({
        project: "./project.inlang",
        outdir: "./ui/paraglide",
        strategy: ["baseLocale"],
        isServer: "false",
        outputStructure: "message-modules",
        emitTsDeclarations: true,
      }),
    ],
  },
  intl: { locales: ["en", "zh"], timeZones: "golden" },
  ignoreClasses: ["lucide", "lucide-*"],
  outDir: "../../dist/pi-agent-wabou/resources",
  globalName: "PiAgentWabouApp",
  themeContrast: "error",
  theme: {
    default: "dark",
    themes: {
      light: {
        appearance: "light",
        colors: {
          canvas: "#f7f7f8",
          surface: "#ffffff",
          "surface-muted": "#f0f0f1",
          input: "#ffffff",
          control: "#f0f0f1",
          "control-hover": "#e8e8e9",
          "control-pressed": "#dededf",
          selected: "#e4e4e5",
          primary: "#242424",
          secondary: "#666666",
          muted: "#707070",
          subtle: "#dededf",
          strong: "#cacacb",
          accent: "#d97745",
          "accent-hover": "#c96d3e",
          "accent-pressed": "#b96137",
          "on-accent": "#242424",
          danger: "#dc3545",
          "danger-hover": "#bd2837",
          "danger-pressed": "#a41f2c",
          "danger-surface": "#fff0f1",
          "danger-primary": "#a41f2c",
          "success-surface": "#eaf8ef",
          "success-primary": "#18794e",
          focus: "#d97745",
        },
      },
      dark: {
        appearance: "dark",
        colors: {
          canvas: "#191919",
          surface: "#1d1d1d",
          "surface-muted": "#232323",
          input: "#202020",
          control: "#252525",
          "control-hover": "#2b2b2b",
          "control-pressed": "#303030",
          selected: "#303030",
          primary: "#e7e7e7",
          secondary: "#b2b2b2",
          muted: "#8a8a8a",
          subtle: "#303030",
          strong: "#3b3b3b",
          accent: "#d97745",
          "accent-hover": "#e18450",
          "accent-pressed": "#c66b3d",
          "on-accent": "#242424",
          danger: "#e5484d",
          "danger-hover": "#f2555a",
          "danger-pressed": "#d63c42",
          "danger-surface": "#3b181b",
          "danger-primary": "#ffb3b5",
          "success-surface": "#153226",
          "success-primary": "#7ce2a7",
          focus: "#8b8bf5",
        },
      },
    },
  },
}));
