import { paraglideVitePlugin } from "@inlang/paraglide-js";
import { defineWabouConfig } from "@wabou/vite";

export default defineWabouConfig({
  vite: {
    plugins: [
      paraglideVitePlugin({
        project: "./project.inlang",
        outdir: "./ui/paraglide",
        strategy: ["baseLocale"],
        isServer: "false",
        emitTsDeclarations: true,
      }),
    ],
  },
  intl: { locales: ["en", "zh"], timeZones: "golden" },
  ignoreClasses: ["lucide", "lucide-*"],
  outDir: "../../dist/pi-agent-wabou/resources",
  globalName: "PiAgentWabouApp",
  theme: {
    default: "light",
    themes: {
      light: {
        appearance: "light",
        colors: {
          canvas: "#f6f7f9",
          surface: "#ffffff",
          "surface-muted": "#f1f3f6",
          input: "#ffffff",
          control: "#f1f3f6",
          "control-hover": "#e7eaf0",
          "control-pressed": "#dce1e9",
          selected: "#e9eef9",
          primary: "#17191f",
          secondary: "#5d6470",
          muted: "#8b93a1",
          subtle: "#e1e5eb",
          strong: "#c7ced8",
          accent: "#5b5bd6",
          "accent-hover": "#4b4bc4",
          "accent-pressed": "#3e3eaa",
          "on-accent": "#ffffff",
          danger: "#dc3545",
          "danger-hover": "#bd2837",
          "danger-pressed": "#a41f2c",
          "danger-surface": "#fff0f1",
          "danger-primary": "#a41f2c",
          "success-surface": "#eaf8ef",
          "success-primary": "#18794e",
          focus: "#5b5bd6",
        },
      },
      dark: {
        appearance: "dark",
        colors: {
          canvas: "#111318",
          surface: "#191c22",
          "surface-muted": "#20242c",
          input: "#20242c",
          control: "#252a33",
          "control-hover": "#303641",
          "control-pressed": "#3a414e",
          selected: "#292e3b",
          primary: "#eef1f5",
          secondary: "#b3bac6",
          muted: "#7f8998",
          subtle: "#303641",
          strong: "#4b5361",
          accent: "#7777e9",
          "accent-hover": "#8585f2",
          "accent-pressed": "#6868d8",
          "on-accent": "#ffffff",
          danger: "#e5484d",
          "danger-hover": "#f2555a",
          "danger-pressed": "#d63c42",
          "danger-surface": "#3b181b",
          "danger-primary": "#ffb3b5",
          "success-surface": "#153226",
          "success-primary": "#7ce2a7",
          focus: "#8b8bf5",
        },
      },
    },
  },
});
