import { paraglideVitePlugin } from "@inlang/paraglide-js";
import { defineWabouConfig } from "@wabou/vite";

export default defineWabouConfig(({ mode }) => ({
  entry: mode === "layout-test" ? "ui/layout-fixtures.tsx" : "ui/index.tsx",
  vite: {
    plugins: [
      paraglideVitePlugin({
        project: "./project.inlang",
        outdir: "./ui/paraglide",
        strategy: ["baseLocale"],
        isServer: "false",
        outputStructure: "message-modules",
        emitTsDeclarations: true,
      }),
    ],
  },
  intl: { locales: ["en", "zh"], timeZones: "golden" },
  ignoreClasses: ["lucide", "lucide-*"],
  outDir: "../../dist/pi-agent-wabou/resources",
  globalName: "PiAgentWabouApp",
  themeContrast: "error",
  theme: {
    default: "light",
    themes: {
      light: {
        appearance: "light",
        colors: {
          canvas: "#f8f8fb",
          surface: "#ffffff",
          "surface-muted": "#f4f5f8",
          input: "#ffffff",
          control: "#f1f3f7",
          "control-hover": "#e9ecf2",
          "control-pressed": "#dfe3eb",
          selected: "#eceafa",
          primary: "#1f2638",
          secondary: "#556077",
          muted: "#687187",
          subtle: "#dde1ea",
          strong: "#d2d7e2",
          accent: "#6a55f2",
          "accent-hover": "#5e49df",
          "accent-pressed": "#5140c7",
          "on-accent": "#ffffff",
          "on-danger": "#ffffff",
          "on-success": "#ffffff",
          danger: "#dc3545",
          "danger-hover": "#bd2837",
          "danger-pressed": "#a41f2c",
          "danger-surface": "#fff0f1",
          "danger-primary": "#a41f2c",
          "success-surface": "#eaf8ef",
          "success-primary": "#18794e",
          focus: "#6a55f2",
        },
      },
      dark: {
        appearance: "dark",
        colors: {
          canvas: "#1e1f22",
          surface: "#2b2d31",
          "surface-muted": "#202124",
          input: "#2b2d31",
          control: "#232428",
          "control-hover": "#303238",
          "control-pressed": "#393b42",
          selected: "#343044",
          primary: "#f4f4f5",
          secondary: "#9ea0a8",
          muted: "#92939a",
          subtle: "#3a3c42",
          strong: "#4a4d55",
          accent: "#6a55f2",
          "accent-hover": "#765ff8",
          "accent-pressed": "#5b47dc",
          "on-accent": "#ffffff",
          "on-danger": "#181818",
          "on-success": "#191919",
          danger: "#e5484d",
          "danger-hover": "#f2555a",
          "danger-pressed": "#d63c42",
          "danger-surface": "#3b181b",
          "danger-primary": "#ffb3b5",
          "success-surface": "#153226",
          "success-primary": "#7ce2a7",
          focus: "#8b8bf5",
        },
      },
    },
  },
}));
