[package]
name = "wabou-terminal-core"
version.workspace = true
edition = "2024"
license.workspace = true

[dependencies]
percent-encoding = "2"
rio-graphics = "0.5.5"
rio-vt = "0.5.5"
rustc-hash = "2"
serde_json = { workspace = true }
teletypewriter = "0.5.5"
tracing = { workspace = true }
wabou-shell-api = { workspace = true }

[target."cfg(unix)".dependencies]
libc = "0.2"
