[package]
name = "wabou-widgets"
version.workspace = true
edition = "2024"

license.workspace = true

[dependencies]
editor-core = "0.5.0"
editor-core-highlight-simple = "0.5.0"
image = {
  workspace = true,
  features = ["bmp", "gif", "jpeg", "png", "webp"]
}
parley = { workspace = true }
tracing = { workspace = true }
vello = { workspace = true }
wabou-shell = { workspace = true }
zeroize = { workspace = true }
