[package]
name = "wabou-widgets"
version = "0.1.0"
edition = "2024"

license.workspace = true

[dependencies]
image = {
  workspace = true,
  features = ["bmp", "gif", "jpeg", "png", "webp"]
}
parley = { workspace = true }
tracing = { workspace = true }
vello = { workspace = true }
wabou-shell = { workspace = true }
zeroize = { workspace = true }
