import { resolve } from "node:path";
import { ROOT, writeGenerated } from "./output.ts";

type BundleFormat = "esm" | "iife";

interface Bundle {
  name: string;
  entries: string[];
  output: string;
  format: BundleFormat;
  minify?: boolean;
  header: string;
}

const bundles: Bundle[] = [
  {
    name: "core prelude",
    entries: [
      "packages/core/src/prelude/bootstrap.ts",
      "packages/core/src/polyfills/abort-controller.ts",
      "packages/core/src/prelude/platform.ts",
    ],
    output: "crates/wabou-runtime/src/gen/core-prelude.js",
    format: "iife",
    minify: true,
    header:
      "// AUTO-GENERATED by scripts/gen-core-prelude.ts. Do not edit by hand.\n",
  },
  {
    name: "Vite runtime",
    entries: ["packages/vite/src/runtime/client.ts"],
    output: "crates/wabou-runtime/src/gen/vite-client.js",
    format: "esm",
    header:
      "// AUTO-GENERATED by scripts/gen-vite-runtime.ts. Do not edit by hand.\n",
  },
  {
    name: "core test runtime",
    entries: ["packages/core/test/runtime-fixture.ts"],
    output: "crates/wabou-runtime/src/gen/test-runtime.js",
    format: "iife",
    header:
      "// AUTO-GENERATED by scripts/gen-test-runtime.ts. Do not edit by hand.\n",
  },
  {
    name: "motion test runtime",
    entries: ["packages/animation/test/runtime-fixture.ts"],
    output: "crates/wabou-runtime/src/gen/motion-test-runtime.js",
    format: "iife",
    minify: true,
    header: "// AUTO-GENERATED by scripts/gen-motion-test-runtime.ts.\n",
  },
  {
    name: "resource test runtime",
    entries: ["packages/core/test/resource-runtime-fixture.ts"],
    output: "crates/wabou-runtime/src/gen/resource-test-runtime.js",
    format: "iife",
    minify: true,
    header: "// AUTO-GENERATED by scripts/gen-resource-test-runtime.ts.\n",
  },
];

async function buildEntry(bundle: Bundle, entry: string): Promise<string> {
  const result = await Bun.build({
    entrypoints: [resolve(ROOT, entry)],
    format: bundle.format,
    target: "browser",
    minify: bundle.minify,
    conditions: ["wabou-source", "browser"],
  });
  if (!result.success) {
    for (const log of result.logs) console.error(log);
    throw new Error(`failed to generate ${bundle.name} from ${entry}`);
  }
  const output = result.outputs.find((file) => file.kind === "entry-point");
  if (!output) throw new Error(`${bundle.name} produced no entry point`);
  // Third-party template literals occasionally contain spaces immediately
  // before a newline. They are not semantically relevant, but make generated
  // artifacts fail `git diff --check`.
  return (await output.text()).replace(/[\t ]+$/gm, "");
}

export async function generateRuntimeBundles(): Promise<void> {
  for (const bundle of bundles) {
    const stages = await Promise.all(
      bundle.entries.map((entry) => buildEntry(bundle, entry)),
    );
    const output = resolve(ROOT, bundle.output);
    const changed = await writeGenerated(
      output,
      bundle.header + stages.join("\n"),
    );
    console.log(`${changed ? "wrote" : "unchanged"} ${output}`);
  }
}
