[package]
name = "wabou"
version.workspace = true
edition = "2024"
description = "Public Rust application API for the Wabou native SolidJS runtime."
readme = "README.md"
publish = false

license.workspace = true

[dependencies]
wabou-runtime = { workspace = true }

[features]
profiling = ["wabou-runtime/profiling"]
vite = ["wabou-runtime/vite"]
