[package]
name = "wabou"
version.workspace = true
edition = "2024"
description = "Public Rust application API for the Wabou native SolidJS runtime."
readme = "README.md"
publish = false

license.workspace = true

[dependencies]
wabou-bindgen = { workspace = true }
wabou-database = { workspace = true }
wabou-runtime = { workspace = true }
wabou-tray = { workspace = true, optional = true }

[features]
bindings = ["wabou-bindgen/generate"]
devtools = ["wabou-runtime/devtools"]
profiling = ["wabou-runtime/profiling"]
rust-hot-reload = ["wabou-runtime/rust-hot-reload"]
tray = ["dep:wabou-tray"]
vite = ["wabou-runtime/vite"]

[dev-dependencies]
serde = { workspace = true, features = ["derive"] }
